### ISSUE TITLE
DiffSharp 0.7: Hard crash inverting large nan matrices

### ISSUE THREAD

**Issue by Lamarth** [DiffSharp/DiffSharp#101]
> open DiffSharp.AD.Float64;;

This is nice:
> Array.replicate 49 (D nan) |> DM.ofArray 7 |> DM.inverse;;
val it : DM = DM [[nan; nan; nan; nan; nan; nan; nan]
                  [nan; nan; nan; nan; nan; nan; nan]
                  [nan; nan; nan; nan; nan; nan; nan]
                  [nan; nan; nan; nan; nan; nan; nan]
                  [nan; nan; nan; nan; nan; nan; nan]
                  [nan; nan; nan; nan; nan; nan; nan]
                  [nan; nan; nan; nan; nan; nan; nan]]

This is odd:
> Array.replicate 64 (D nan) |> DM.ofArray 8 |> DM.inverse;;
val it : DM =
  DM
    [[nan; 6.952457011e-310; 3.952525167e-323; 4.243991586e-314;
      8.487983165e-314; 1.273197475e-313; 1.697596633e-313; 0.0]
     [nan; nan; nan; nan; nan; nan; nan; nan]
     [nan; nan; nan; nan; nan; nan; nan; nan]
     [nan; nan; nan; nan; nan; nan; nan; nan]
     [nan; nan; nan; nan; nan; nan; nan; nan]
     [nan; nan; nan; nan; nan; nan; nan; nan]
     [nan; nan; nan; nan; nan; nan; nan; nan]
     [nan; nan; nan; nan; nan; nan; nan; nan]]

This is distressing:
> Array.replicate 81 (D nan) |> DM.ofArray 9 |> DM.inverse;;
PS C:\Windows\System32>

>Faulting application name: fsiAnyCpu.exe, version: 10.800.20.18106, time stamp: 0xd0e394f5
Faulting module name: clr.dll, version: 4.8.4150.0, time stamp: 0x5e176fc2
Exception code: 0xc0000005
Fault offset: 0x00000000000810c3
Faulting process id: 0x56ec
Faulting application start time: 0x01d622d92cbff942
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsiAnyCpu.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 5bbbc2e5-8eed-4109-8842-b2f3ee2daef5
Faulting package full name: 
Faulting package-relative application ID: 

>Application: fsiAnyCpu.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFBD63110C3 (00007FFBD6290000) with exit code 80131506.

This affects both the current stable and beta versions - though the message refers to libopenblas.dll in the stable version.

**Comment by gbaydin** [comment]
Hi @Lamarth I would say that a matrix filled with `nan` values is not an [invertible matrix](https://en.wikipedia.org/wiki/Invertible_matrix) so computing its inverse should consistently fail and we should have thrown an error like "Cannot invert the given matrix".

In general many other operations are not defined when a value has `nan`, `inf` or `-inf` in it. We're currently working on the new DiffSharp version >1.0 with general Tensor support (generalizing vectors and matrices in older DiffSharp). I will keep your feedback in mind when implementing the inverse operation there.

**Comment by Lamarth** [comment]
Thanks @gbaydin - I would be quite happy with a thrown error. I'm grabbing the Hessian and immediately inverting it for Newton's Method. When the value is infinity, the Hessian is all nan, and the inverse is crash without catch or stack trace.

**Comment by dsyme** [comment]
@gbaydin What's your plan for matrix inversion in DiffSharp 1.0?  Should I add it to the list of things I'm tracking in #69 ?

**Comment by gbaydin** [comment]
Yes we definitely need to implement matrix inversion, and I was thinking about doing that soon. There is existing generic matrix inversion code in F# I wrote some years ago, here: https://github.com/gbaydin/FsAlg/blob/master/src/FsAlg/Matrix.fs#L205 (which can be used for the Reference backend), and I think probably we already have matrix inversion available in TorchSharp.
