### ISSUE TITLE
Bug in Backend.OpenBLAS.fs

### ISSUE THREAD

**Issue by grek142** [DiffSharp/DiffSharp#11]
Hallo,

At first congratulations to this library, but I've found two little bugs in module LAPACK in function ssysv and dsysv, which make these functions useless.
You must correct line 487 from: use arg_b = new PinnedArray<float32>(b)
to use arg_b = new PinnedArray<float32>(b')
and similar (variable b -> b') in line 580.

Enrico

**Comment by gbaydin** [comment]
Hi! Thank you for reporting this. I will look into it and let you know.

**Comment by grek142** [comment]
Ok, if you look deeper into the OpenBLAS module then there is (maybe?) another issue.
In my opinion the matrices in the DM module are in row major order, but LAPACK assume per default column major order. This is not a problem if you've only symmetric matrices, but in all other cases.
If this is really an issue, then you have three possible solutions.
1. DiffSharp use per default column major order
2. swap the indexers
3. use the LAPACKE interface (if OpenBLAS has one), then you can define the order. But this can eventually slowdown the calculations

**Comment by mrakgr** [comment]
I've checked into that and currently there is a [bug](https://github.com/xianyi/OpenBLAS/issues/717) in the latest release of OpenBLAS that prevents the LAPACKE function from being used in row major format. I've worked around that by adding manual transposes and solved these issues in the latest pull request.

**Comment by brada4** [comment]
It is bug in LAPACKE, you can check with generic LAPACK 3.6.0

**Comment by gbaydin** [comment]
I can confirm that the bugs you pointed out in `ssysv` and `dsysv` caused incorrect return values. This is now fixed in the repo.

**Comment by gbaydin** [comment]
Regarding @grek142's mention of another issue about LAPACK row- and column-major order:

I do not see any bug related with that.

.NET arrays are stored in memory using row-major order and the library will continue using these. We are aware of LAPACK's way of working with matrices and we designed our wrapper code paying attention to this.

To make sure that we have a better way of catching similar bugs in future, I have now implemented unit tests for the backend interface. Everything with the OpenBLAS backend seems to be working fine, including operations `SolveSymmetric_M_V`, `Inverse_M`, and `Det_M`.

If you encounter a bug where any operation gives incorrect result, please do let us know by opening a separate issue for that, showing a minimal example producing incorrect output.

Also, I have not experienced any unexpected behavior with the LAPACK implementation in OpenBLAS.

**Comment by grek142** [comment]
Ok, thank You. As You said this was just a mention not really a bug in the library.
(I just saw the problem as I'd wrote my own wrapper for LAPACK to work with the raw data of a hessian matrix. For simplicity I'd used the dposv and dpotri methods and this was not the best choice with the benefit of hindsight.)

**Comment by gbaydin** [comment]
Thank you. :)
