### ISSUE TITLE
proposal for user choice of packages

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#111]
Follow on from #106 

After discussing with @gbaydin today my proposal is that we remove the DiffSharp pacakge and have these three "top-level-entry-point" packages:

* package `DiffSharp-torch-cpu`
      (references DiffSharp.Core, DiffSharp.Backends.Torch, libtorch-cpu)

* package `DiffSharp-torch-cuda-10.2-win-x64`
       (references DiffSharp.Core, DiffSharp.Backends.Torch, libtorch-cuda-10.2 for windows)

* package `DiffSharp-torch-cuda-10.2-linux-x64`
      (references DiffSharp.Core, DiffSharp.Backends.Torch, libtorch-cuda-10.2 for linux)

If we have other backends that are high quality and fully feature-complete and tested we can add those too.

With this, the user on a Jupyter notebook simply references one of these and a version number, e.g.

    #r "nuget: DiffSharp-torch-cpu, 1.0.3"

That's a nice and simple choice isn't it? 

Note we really have to split windows/linux Cuda packages here because the downloads are v. large.

Note I haven't listed an accumulation package for the reference backend. I think people wanting to use the reference backend are likely to be building new DiffSharp library components (e.g. derived algorithms) or extensions (new backends etc.) and should reference the individual packages they need.  For example they reference `DiffSharp.Core` in their library project and `DIffSharp.Backend.Reference` in their test project (and a few more packages if they want to test on Torch).  That actually gives a really nice, light experience for creating a library project that adds some stuff to DiffSharp - no need to download anything Torch related if you're happy to trust the reference backend for testing.

Aside : With this, the user gets whatever is the latest version of Torch the `TorchSharp` we depend on happens to work on.  In some far future I could see people wanting to vary the Torch between two or three recent versions, so you can imagine this

* package `DiffSharp-torch-1.5-cpu`
* package `DiffSharp-torch-1.6-cpu`
* package `DiffSharp-torch-1.5-cuda-10.2-linux-x64`
* package `DiffSharp-torch-1.6-cuda-10.3-linux-x64`

etc.  It's an interesting question which of these the user is most likely to want to vary on.  (and will they want to use nightly or modified or patched versions of Torch? That would be hard...)

**Comment by gbaydin** [comment]
Hi @dsyme I have given this more careful thought after our discussion, and the way you summarized things clearly here helped me understand the options better.

Just to list this here for easier reference later, another alternative we can do is:
- We keep the `DiffSharp` package that references `DiffSharp.Core` and `DiffSharp.Backends.Reference`
- `DiffSharp` package can also reference one of (`DiffSharp.Backends.MKL` + `Microsoft.ML.Mkl.Redist`) or (`DiffSharp.Backends.Torch` +  `libtorch-cpu`) as well. The former is about 89 MB (linux+osx+win) and the latter around 148 MB (linux+win currently).

When we need to use other backends in dotnet interactive, we would use extra `#r` entries like:

```
#r "nuget: DiffSharp"
#r "nuget: DiffSharp.Backends.Torch.CUDA.Linux"
```
In the example above, the package `DiffSharp.Backends.Libtorch.CUDA.Linux` would reference `DiffSharp.Backends.Torch` +  `libtorch-cuda-linux`.

I think this was your original suggestion, instead of the "flattening the matrix" idea that I was thinking about.

When I started writing this comment, I was actually going to propose the setup I summarized in this message. But as I kept thinking about your proposal above, I think makes more sense. Still thinking. :)

**Comment by gbaydin** [comment]
For ***option A***, I think it would be good to have also the accumulation package `DiffSharp-reference` (or some other name like `DiffSharp-basic`) that references `DiffSharp.Core` and `DiffSharp.Backends.Reference`. This is a very lightweight and useful config that can be used for simple tasks and experiments that don't involve heavy linear algebra. There are such usage cases in automatic differentiation of scalars. If we're careful with the naming, we can avoid users taking it as the "standard" DiffSharp distribution.

**Comment by gbaydin** [comment]
One important worry I have about the naming scheme in ***option A*** is that a name like `DiffSharp-torch-1.5-cuda-10.2-linux-x64` can give the impression that DiffSharp is "just another dotnet wrapper" of PyTorch tensors, autodiff, neural nets etc., which it is not. DiffSharp can have a libtorch backend that uses libtorch tensors for raw tensors (without autodiff), among other backends. I think we need to be careful with this aspect when naming. 

Perhaps one solution is: if we commit to the choice of libtorch rawtensors as the main backend, we can just use the naming `DiffSharp-cuda-10.2-linux-x64` etc. and clarify in the user documentation the details of how libtorch is used as a backend.

**Comment by dsyme** [comment]
> Perhaps one solution is: if we commit to the choice of libtorch raw tensors as the main backend...

This would likely be fine for now, though I'm aware an ONNX Runtime backed is of real interest.  I guess that could add the name '-onnx-'.   It would be nice not to bake this in any further than the surface user experience in application scripts.

Separately, there is also the question of what the default backend is once packages are referenced. Today the default backend is always Reference.  It obviously sucks to always do 

    dsharp.zeros(backend=Torch)

I suppose option A might allow us to set the default backend automagically on package reference (I'm not sure how, but I guess it could happen - it would have to be setting a global or adjusting the default backend detection logic).  Alternatively the programmer needs one of these:

1. require

       let dsharp = DiffSharp.Configure(backend=Torch)

2. set a global

       DiffSharp.Configure(backend=Torch)

I guess in practice we'll just set a global and adjust the default logic to "do the right thing", and report it to the user.

**Comment by dsyme** [comment]
OK so the Option A proposal would be

* package `DiffSharp-cpu`
       (references DiffSharp.Core, DiffSharp.Backends.Torch, libtorch-cpu)

* package `DiffSharp-cuda-win`
       (references DiffSharp.Core, DiffSharp.Backends.Torch, libtorch-cuda-10.2-win-64)

* package `DiffSharp-cuda-linux`
       (references DiffSharp.Core, DiffSharp.Backends.Torch, libtorch-cuda-10.2-linux-x64)

* package `DiffSharp-reference`
       (references DiffSharp.Core, DiffSharp.Backends.Reference)

The user on a Jupyter notebook simply references one of these and a version number, e.g.

#r "nuget: DiffSharp-cpu, 1.0.3"

They get the latest version if they drop the version number. Nice and simple! :-)

Extension libraries that simpliy define new things in terms of existing primitives would reference just `DiffSharp.Core` (the corresponding test projects would test against whatever backends the user likes). Extensions that reveal more native Torch functionality would look [something like this](https://github.com/DiffSharp/DiffSharp/pull/89#issuecomment-633101964).

**Comment by gbaydin** [comment]
> Separately, there is also the question of what the default backend is once packages are referenced. Today the default backend is always Reference. 

I think it makes sense to have some functionality like `setDefaultDType`, `setDefaultDevice`, `setDefaultBackend`. PyTorch has something similar for setting the default tensor type: https://pytorch.org/docs/stable/torch.html#torch.set_default_tensor_type

**Comment by dsyme** [comment]
OK. Can we just do

      dsharp.Configure(?backend, ?device, ?dtype)

i.e.

      dsharp.Configure(backend=Torch)
      dsharp.Configure(dtype=Float64, backend=Torch)
      dsharp.Configure(dtype=Float64, device=GPU, backend=Torch)

or do you want these too?

      dsharp.DefaultDType <- Float64
      dsharp.DefaultDevice <- GPU
      dsharp.DefaultBackend <- Backend.Torch

Thanks

**Comment by gbaydin** [comment]
> dsharp.Configure(?backend, ?device, ?dtype)

Sounds good! Maybe just call it `dsharp.config(?backend, ?device, ?dtype)`? I think this should be enough.

**Comment by dsyme** [comment]
cool, i'll add that then

**Comment by dsyme** [comment]
Closing as this has been implemented
