### ISSUE TITLE
Check and fix dilations in libtorch backend

### ISSUE THREAD

**Issue by gbaydin** [DiffSharp/DiffSharp#116]
Dilation code in the libtorch backend seems incomplete for some cases. We need to check the behavior and fix it and ensure all tests are passing without excluding the libtorch backend. `scatter` can be helpful to reimplement dilations.

See here: https://github.com/DiffSharp/DiffSharp/pull/106#discussion_r429654697

**Comment by dsyme** [comment]
Yup, it needs a complete rewrite in terms of Scatter.

**Comment by gbaydin** [comment]
Closing as this is now fixed in #106
