### ISSUE TITLE
Enhancement : Way to use it in FSI

### ISSUE THREAD

**Issue by Dref360** [DiffSharp/DiffSharp#12]
When trying to use DiffSharp in FSI (FSharp interactive) I always get : Unable to load DLL 'libopenblas':
But when I run it, everything is fine.

FSI is running in x64 with debugging enabled.

**Comment by gbaydin** [comment]
This is related with the general behavior of F# Interactive and native dlls. It is not specific to this library.

[This page](http://christoph.ruegg.name/blog/loading-native-dlls-in-fsharp-interactive.html) provides a detailed overview of how to approach this.

Assuming you are running Windows, please try one of these methods:

#### 1

Place copies of the DiffSharp assembly (`DiffSharp.dll`) and the files needed for OpenBLAS (`libopenblas.dll`, `libgcc_s_seh-1.dll`, `libgfortran-3.dll`, `libquadmath-0.dll`) into the same folder with the F# script you are running and add this to the beginning of your F# script.

```fsharp
System.Environment.CurrentDirectory <- __SOURCE_DIRECTORY__
```

#### 2
You are loading the DiffSharp assembly at the beginning of an F# script with a statement like

```fsharp
#r "../DiffSharp.dll"
```

make sure that copies of all the OpenBLAS dlls mentioned above are found in the same folder with the `DiffSharp.dll` you are loading.

Please tell me if this helps.

**Comment by Dref360** [comment]
It works!
Thanks a lot!
