### ISSUE TITLE
Documentation generation

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#134]
TODO

* [ ] decide on which documentation generation framework to use

**Comment by gbaydin** [comment]
An option I wanted to check is this https://github.com/dbrattli/sphinxcontrib-fsharp because [sphinx](https://www.sphinx-doc.org/en/master/) is very stable and very widely used.

**Comment by dsyme** [comment]
We should check it out, but on a quick glance there's not much added from the OCaml base it is forking from, which would be problematic (e.g. not sure there's any support there for F# object programming) https://github.com/jacquev6/sphinxcontrib-ocaml/compare/master...dbrattli:master

**Comment by gbaydin** [comment]
Another option that I really like

**Comment by gbaydin** [comment]
Another option that I really like

**Comment by gbaydin** [comment]
Another option that I really like

https://github.com/mkdocs/mkdocs/
https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#f

Here is a nice-looking example website that was created with mkdocs: https://www.mackelab.org/sbi/

**Comment by dsyme** [comment]
Stylistically they look ok but the absense of any F# language support means that would have to be added.  The problem would be similar to reimplementing large parts of FSharp.Formatting.

Perhaps we could take their style and use that as the template for FSharp.Formatting output

**Comment by dsyme** [comment]
@gbaydin I think it's a tradeoff between 

1. using some python-like system without any F# literate scripting/programming support (so no checking/inference/tooltips for documentation)

2. using FSharp.Formatting with F# literate scripting as in https://github.com/DiffSharp/DiffSharp/pull/138 

There are tradeoffs

| | F# literate docs | Python doc tools |
|:-------::-----------:|:---------:|
| Checked scripts | yes | no |
| Can reuse examples for notebooks | [yes](https://github.com/fsprojects/fsharp-ai-tools/blob/master/tools/fsx2nb.fsx)) | no |
| It's what Gunes wants | half |  yes | 
| We have control over stack | yes |  half | 
| Complexity | medium |  medium | 
| Visually fresh | needs refreshed template |  yes | 
| API generation | yes (needs work) |  no (needs a lot of work) | 


I'm not yet happy with the Fornax doc scripting in https://github.com/DiffSharp/DiffSharp/pull/135 but it may also be an option, it is based on the same things as F# literate docs

**Comment by dsyme** [comment]
Worth checking out MiniScaffold generated docs as well, e.g. 

https://www.jimmybyrd.me/miniscaffold-docs-test/

Templates can vary.  It has good F# support (it's built for F#)
