### ISSUE TITLE
Printing of tensors should show dtype, device

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#140]
In #138 I did a trial port of the DiffSharp 0.7 samples from the DiffSharp 0.7 documentation.

I'm also walking through some pytorch tutorials and will note further minor things missing in this list:

* [x] `dsharp.empty`  (for `torch.empty` - uninitialised tensors)
* [x] simple `print` function where `let print x = printfn "%A" x` seems reasonable to add to DiffSharp
* [ ] printing of tensors can be improved and should generally follow Torch.  For example `dtype` is shown when it is not the default one.  I'll make a separate issue on this

**Comment by dsyme** [comment]
I'm also walking through some pytorch tutorials and will note further minor things missing in this list:

* [ ] `dsharp.empty`  (for `torch.empty` - uninitialised tensors)

**Comment by gbaydin** [comment]
> dsharp.empty (for torch.empty - uninitialised tensors)
> simple print function where let print x = printfn "%A" x seems reasonable to add to DiffSharp

I support all of these, especially these last two. :) I've been feeling the need for `dsharp.empty` many times and kept postponing the implementation.

**Comment by dsyme** [comment]
This was done a while back, printing now shows characteristics when they are not the same as the current defaults
