### ISSUE TITLE
Test failures with win CUDA 10.2

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#147]
I'm running latest tests on Windows with cuda support (Geforce 2080 Ti) using branch #146 

Current failures:

![image](https://user-images.githubusercontent.com/7204669/85925262-1461a880-b88f-11ea-871e-363b9eaafa95.png)

* [x] TestTensorConv1D: failing for integer types, SEHException 
* [x] TestTensorDot: failing on Int8 (maybe others too)
* [x] TestTensorFlip: "InteropServices.ExternalException: '"flip_cuda" not implemented for 'Bool'"
* [x] TestTensorMatMulT2T2:     System.Runtime.InteropServices.SEHException : External component has thrown an exception. `THSTensor_mn`

**Comment by dsyme** [comment]
I've fixed some of these errors, working through the remainder

Just to note some tests are taking a long time to run on GPU

![image](https://user-images.githubusercontent.com/7204669/85925006-bbdddb80-b88d-11ea-8f5f-c0abece6fed0.png)

**Comment by dsyme** [comment]
Ah the failure in `` is caused by the failure in GetHashCode for GPU tensors

We should should verify that we want to use hashing on tensors like this, and if it's possible to do a faster hashing on TorchTensor (currently it fails and the way it's written would be very slow on GPU)

```
                    let uniques = Dictionary<'T, Tensor>()
                    for i = 0 to _values.Length-1 do
                        let v, lw = _values.[i], _categorical.logits.[i]
                        if uniques.ContainsKey(v) then
                            let lw2 = uniques.[v]
                            uniques.[v] <- dsharp.stack([lw; lw2]).logsumexp(dim=0)
                        else uniques.[v] <- lw
                    copyKeys uniques, dsharp.stack(copyValues uniques).view(-1)
```

**Comment by dsyme** [comment]
@gbaydin The remaining three errors are where integer operations are failing on GPU.

* TestTensorConv1D: failing for integer types
* TestTensorDot and TestTensorMatMulT2T2: torch::mm is failing on all integer types

I debugged the issue a little.  One call stack is [here](https://gist.github.com/dsyme/19ffe7f268b39c34b927f2f06e936270).  After a bit of debugging the second reveals this error text hanging around on the callstack:

```
"addmm for CUDA tensors only supports floating-point types. Try converting the tensors with .float()" | const char *
```

So it looks like Torch CUDA limits `addmm`.  If a major platform like that has that limitation I suppose it's ok for us to have it too.
As a result I propose we make both the reference implementation and torch backend fail on integer types for all of `conv1d`, `conv2d`, `conv3d` and  `mm`, at least for GPU.

To clarify, we must choose between the following options for `conv1d`, `conv2d`, `conv3d` and  `mm` on integer types:

1. Make them all fail for Torch GPU only
2. Make them all fail for any GPU call (including the reference implementation, which fakes GPU for testing purposes)
3. Make them all fail for all CPU and GPU calls (including the reference implementation)
4. Fix up the torch backend implementations to convert to Float32/Float64.

@gbaydin Let me know which these you want.  For now I will do (4) I guess.

**Comment by dsyme** [comment]
@VisualMelon reporting all tests currently passing on GPU device

**Comment by gbaydin** [comment]
@dsyme I think (3) is also a good choice. I I think integer types in general convolutions are not supported on many systems including PyTorch and Tensorflow.

One use case of integer convolutions is with quantized models. For example here: https://pytorch.org/docs/stable/quantization.html

So PyTorch makes separate quantized convolution implementations under `torch.nn.quantized` that work with integers. I think this is mainly because there is no support for these in GPU backends. They state currently these only work efficiently on some CPU backends. We can perhaps rely on these through libtorch at some point.

**Comment by gbaydin** [comment]
If we choose (4), I think we should raise a [warning](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.warningexception?view=netcore-3.1) saying that the user is doing an integer convolution and internally we are running this as a floating point convolution.
