### ISSUE TITLE
Remove hashing on tensors

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#149]
Two of the current failures on GPU are to do with hashing on tensors.

However PyTorch doesn't support efficient content-based hashing of tensors on CPU or GPU, see https://github.com/pytorch/pytorch/issues/2569

As a result I propose that we remove hashing on tensors apart from scalars.  THis aligns with only allowing ordered IComparable comparison on scalars.

**Comment by dsyme** [comment]
See also https://github.com/DiffSharp/DiffSharp/issues/147#issuecomment-650572227

@gbaydin What are your thoughts on this - in the linked code you use hashing via dictionaries.  Are those values scalars?  I don't think so?

What's the right exepctation here, e.g. with respect to PyTorch code?

**Comment by dsyme** [comment]
For now I will add this to ComputeHash for TorchRawTensor

```
        // Torch Tensors must be CPU before DataItem can be accessed
        let tt = torchMoveTo tt Device.CPU
```

**Comment by dsyme** [comment]
The choices

1. move to CPU

2. limit hahing to scalars only

3. do hashing be reference identity (yuck)

4. disallow hashing on tensors altogether

**Comment by gbaydin** [comment]
> See also #147 (comment)
> @gbaydin What are your thoughts on this - in the linked code you use hashing via dictionaries. Are those values scalars? I don't think so?

In the linked code, the values getting hashed can be anything, not just scalars. Have I understood the question correctly? By the way that use case (combine duplicates in the Empirical distribution) should happen very rarely in practice. The main use case would be a probabilistic programming system.

I think out of the options listed, moving to CPU for hashing sounds good. I think this is the current behavior for the Torch backend now.

**Comment by dsyme** [comment]
> In the linked code, the values getting hashed can be anything, not just scalars. Have I understood the question correctly? 

Yes

> I think out of the options listed, moving to CPU for hashing sounds good. I think this is the current behavior for the Torch backend now.


OK cool
