### ISSUE TITLE
Forward on forward mode question

### ISSUE THREAD

**Issue by mrakgr** [DiffSharp/DiffSharp#15]
let inline r x y = (x*x)*(y*y)

    let a = D 3.0f |> makeForward 0u (D 1.0f)
    let a' = a |> makeForward 1u (D 1.0f)

    let b = D 2.0f |> makeForward 0u (D 0.0f)
    let b' = b |> makeForward 1u (D 0.0f)

    let q = r a' b'

I am wondering whether it would be possible to take second derivatives using forward on forward. I already know how to do it using reverse over forward, but I've read that forward on forward should be possible as well.

**Comment by gbaydin** [comment]
What you are doing is already correct. :)

The 2nd derivative of `(x^2) * (y^2)` with respect to `x` is `2 * (y^2)`. Evaluated at x = 3, y = 2, the result is 8.

If you run your code and take two tangents,

```fsharp
let q = r a' b' |> tangent |> tangent
```
you get

```fsharp
val q : D = D 8.0f
```
and this is computed with forward on forward.

The preferred way of doing this is to use `diff`, which works with forward AD, so you don't have to worry about tags and tangents:

```fsharp
let q2 = diff (diff (fun x -> r x (D 2.f))) (D 3.f)
```

which would give the same result

```
val q2 : D = D 8.0f
```

**Comment by gbaydin** [comment]
There is also `diff2` that is specifically for forward-on-forward and `diffn` which stacks the forward mode `n` times to get the `n`th derivative.

```fsharp
let q3 = diff2 (fun x -> r x (D 2.f)) (D 3.f)
let q4 = diffn 2 (fun x -> r x (D 2.f)) (D 3.f)

```

**Comment by mrakgr** [comment]
Ah, right. I worded my question badly. What I really meant to ask was whether it was possible to calculate the Hessian using forward on forward. For the above example it comes to this:

    val it : D * DM = (D 36.0f, DM [[18.0f; 24.0f]
                                    [24.0f; 8.0f]])

I can get a single column using forward and then the reverse like so:

    let a = D 3.0f |> makeForward 0u (D 0.0f)
    let a' = a |> makeReverse 1u

    let b = D 2.0f |> makeForward 0u (D 1.0f)
    let b' = b |> makeReverse 1u

    let q = r a' b'

    q |> reverseProp (D 1.0f)

    a'
    b'

It is also possible to take the diagonal elements using the example above. What I meant to ask is, purely out of curiosity, whether it was possible to take the non diagonal elements using forward on forward.

One way that I've discovered is like this:

    let a = D 3.0f |> makeForward 0u (D 1.0f)
    let a' = a |> makeForward 1u (D 1.0f)

    let b = D 2.0f |> makeForward 2u (D 1.0f)
    let b' = b |> makeForward 3u (D 1.0f)

    let q = r a' b'

If one sets the perturbation tags like so, it will go deeper and calculate all sorts of derivatives:

    DF
        (DF
           (DF (DF (D 36.0f,D 24.0f,0u),DF (D 24.0f,D 8.0f,0u),1u),
            DF (DF (D 36.0f,D 24.0f,0u),DF (D 24.0f,D 8.0f,0u),1u),2u),
         DF
           (DF (DF (D 36.0f,D 24.0f,0u),DF (D 24.0f,D 8.0f,0u),1u),
            DF (DF (D 18.0f,D 12.0f,0u),DF (D 12.0f,D 4.0f,0u),1u),2u),3u)

I can see a 18 and 8 and 24 in there (a whole bunch of them,) so I can tell that it is calculating the Hessian among others, but I cannot see a way to do it on an even level. For example:

    let a = D 3.0f |> makeForward 0u (D 0.0f)
    let a' = a |> makeForward 1u (D 0.0f)

    let b = D 2.0f |> makeForward 0u (D 0.0f)
    let b' = b |> makeForward 1u (D 0.0f)

    let q = r a' b'

The above does not give me the first row and column of the Hessian but simply zero.

    let a = D 3.0f |> makeForward 0u (D 1.0f)
    let a' = a |> makeForward 1u (D 1.0f)

    let b = D 2.0f |> makeForward 0u (D 1.0f)
    let b' = b |> makeForward 1u (D 0.0f)

    let q = r a' b'

The above example gives me 32 as the second derivative which is obviously wrong.

Maybe this is a misunderstanding on my part and forward on forward is really made to be used for Hessians.

**Comment by gbaydin** [comment]
There are several ways of computing a Hessian with only the forward mode.

An excellent reference for AD and Hessians is Laurence Dixon's paper:

L. Dixon, Automatic Differentiation: Calculation of the Hessian, In: Encyclopedia
of Optimization. 2001.
http://dx.doi.org/10.1007/0-306-48332-7_17

This is the most accessible and practical explanation of the subject that I've seen.

We had an implementation of Dixon's "triplets" in version 0.6 of DiffSharp. It was called `AD.Specialized.ForwardGH`. It basically keeps a gradient vector and Hessian matrix attached to every scalar in your system. When you evaluate the function forward, you can get the Hessian with just one forward AD evaluation (that is, not two forward evaluations, or forward-on-forward).

However this approach was based on keeping the scalar elements of a vector or matrix as separate entities with their assigned tags and all the other stuff. It was a big obstacle to run things with BLAS, for example.

DiffSharp currently evaluates Hessian related operations with (`hessian`, `hessianv` etc.) with forward-on-reverse and reverse-on-forward.

If you want a forward-on-forward Hessian with DiffSharp 0.7, you can force it by defining forward AD operations for `grad` and `jacobian`:

```fsharp
// Evaluate a gradient with forward AD
let inline gradForward (f:DV->D) (x:DV) =
    Array.init x.Length (fun i -> jacobianv f x (DV.standardBasis x.Length i)) |> toDV

// Evaluate a Jacobian with forward AD
let inline jacobianForward (f:DV->DV) (x:DV) =
    Array.init x.Length (fun i -> jacobianv f x (DV.standardBasis x.Length i)) |> DM.ofCols
```

Both use the Jacobian-vector product `jacobianv`, which is essentially the fundamental block of forward AD.

Then you can combine these for getting a forward-on-forward Hessian. Using your example function `r(x,y) = (x^2) * (y^2)`, at x=3 and y=2:

```fsharp
let r (x:DV) = x.[0] * x.[0] * x.[1] * x.[1]
let h = hessian r (toDV [3; 2])

val r : x:DV -> D
val h : DM = DM [[8.0f; 24.0f]
                 [24.0f; 18.0f]]
```

For doing the same with only the forward mode, follow these steps:

`r` is a vector-to-scalar function, make a vector-to-vector function that will map the input of `r` at any point to the gradient of `r` at that point:

```fsharp
let gr x = gradForward r x

val gr : x:DV -> DV
```

If you take the Jacobian of this, you get the Hessian:

```fsharp
let hr x = jacobianForward gr x
val hr : x:DV -> DM
```

Evaluate:
```fsharp
let h2 = hr (toDV [3; 2])

val h2 : DM = DM [[8.0f; 24.0f]
                  [24.0f; 18.0f]]
```

**Comment by mrakgr** [comment]
let a = D 3.0f |> makeForward 0u (D 1.0f)
    let a' = a |> makeForward 1u (D 1.0f)

    let b = D 2.0f |> makeForward 0u (D 0.0f)
    let b' = b |> makeForward 1u (D 0.0f)

    let q = r a' b'

    let a2 = D 3.0f |> makeForward 0u (D 1.0f)
    let a2' = a2 |> makeForward 1u (D 0.0f)

    let b2 = D 2.0f |> makeForward 0u (D 0.0f)
    let b2' = b2 |> makeForward 1u (D 1.0f)

    let q2 = r a2' b2'

    let a3 = D 3.0f |> makeForward 0u (D 0.0f)
    let a3' = a3 |> makeForward 1u (D 1.0f)

    let b3 = D 2.0f |> makeForward 0u (D 1.0f)
    let b3' = b3 |> makeForward 1u (D 0.0f)

    let q3 = r a3' b3'

    let a4 = D 3.0f |> makeForward 0u (D 0.0f)
    let a4' = a4 |> makeForward 1u (D 0.0f)

    let b4 = D 2.0f |> makeForward 0u (D 1.0f)
    let b4' = b4 |> makeForward 1u (D 1.0f)

    let q4 = r a4' b4'

Yeah, I must have made a mistake the first time around and came to a misunderstanding. For the above example, one can also calculate the Hessians manually by iterating as in the above. I get it now.

Thank you for the explanation.
