### ISSUE TITLE
Default printing of tensors in notebooks causes exception

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#152]
The default printing of scalar tensors in F# .NET Interactive notebooks causes an exception:

1. create an F# notebook at https://mybinder.org/v2/gh/dotnet/interactive/master?urlpath=lab

2. Run this

```
#i "nuget: https://ci.appveyor.com/nuget/diffsharp"
#r "nuget: DiffSharp-lite,0.9.5-preview-2006281542" // update version as needed, see a recent build in https://ci.appveyor.com/project/dsyme/diffsharp/history

open DiffSharp

dsharp.tensor 3.0
```

Expected: nice printing of tensor

Actual: exception "Cannot enumerate Tensor with dim "

Oddly also applies to tensors of any dimension.

```
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1639.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1639
   at DiffSharp.Tensor.System-Collections-Generic-IEnumerable`1-GetEnumerator()
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at Microsoft.DotNet.Interactive.Formatting.EnumerableExtensions.TakeAndCountRemaining[T](IEnumerable`1 source, Int32 count) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\EnumerableExtensions.cs:line 19
   at Microsoft.DotNet.Interactive.Formatting.HtmlFormatter`1.<>c__DisplayClass7_0.<CreateForSequence>g__BuildTable|3(T source, TextWriter writer) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive.Formatting\HtmlFormatter{T}.cs:line 112
```

**Comment by dsyme** [comment]
@gbaydin The problem stems from this:

https://github.com/DiffSharp/DiffSharp/commit/87cc85ca690344272046df4ed38196f08a28e50a

and the decision to have `Tensor` implement `IEnumerable<Tensor>`.  

I know what you're trying to do here but I believe this isn't really going to fly. There's just a lot of .NET tooling that takes values and attempts to do some kind of display on them.  It inevitably means that using "enumerate a collection" logic which is all over .NET will fail when it eaches the base case of scalars.

We could try and work around this in each and every case (e.g. install pretty printers into notebooks etc.) but it's going to be a losing battle.

Anyway I suggest it's probably best we don't do this.  We can't emulate Python in every way

**Comment by gbaydin** [comment]
So I investigated a bit and found about the following:

https://github.com/dotnet/interactive/issues/63
https://github.com/dotnet/interactive/issues/569
https://github.com/dotnet/interactive/issues/642

and the PR
https://github.com/dotnet/interactive/pull/705

I really like the "Make '%A' structured formatting be the default for F# plaintext" solution. When that is merged, the Tensor printing should also be fine, as I understand.

**Comment by gbaydin** [comment]
I also tried to set
```fsharp
Formatter<DiffSharp.Tensor>.Register(fun t -> sprintf "%A" t)
```
as described here https://github.com/dotnet/interactive/blob/main/docs/formatting.md but I couldn't get it to work so far.

**Comment by dsyme** [comment]
> I really like the "Make '%A' structured formatting be the default for F# plaintext" solution. When that is merged, the Tensor printing should also be fine, as I understand.

Well, I do just think a lot of .NET stuff may have a problem with an infinite unrolling of IEnumerable.  It's just asking for trouble...

Also is IEnumerable on Tensor even that useful?  I think something like that should be an explicit conversion, given 

1. iterating in whichever order
2. losing any sparseness
3. losing device
4. the thing may be huge in one or more dimensions

**Comment by dsyme** [comment]
@gbaydin I haven't tried but to check you're using latest master use this link:

> https://mybinder.org/v2/gh/dotnet/interactive/master?urlpath=lab

**Comment by dsyme** [comment]
> If we can figure out this fix, perhaps we can keep the IEnumerable (i.e., not merge #153 ) and still solve the printing issue. Please tell me what do you think. Did the printing work for you when you unrolled IEnumerable?

I will check again now

**Comment by gbaydin** [comment]
> Well, I do just think a lot of .NET stuff may have a problem with an infinite unrolling of IEnumerable. It's just asking for trouble...

Ok, I'm convinced. We can merge #153 and move on. I think the Tensor -> IEnumerable use case is also available through the `.unstack()` method that you used in the PR.

I think the formatter for dotnet interactive is a separate issue we can work on.

**Comment by dsyme** [comment]
thanks!
