### ISSUE TITLE
Grad doesn't work when creating new tensors by copying values from existing ones

### ISSUE THREAD

**Issue by mgorinova** [DiffSharp/DiffSharp#156]
Hi, I encountered a bug where the gradient can't be computed when a new tensor is created using copied values from the input (using `tensor.Item(...)` or `tensor.GetSlice(...)`).  A minimal example reproducing the bug is the function `fn2` bellow:

```F#
    let fn1 (x:Tensor) = 
        x.sum()

    let fn2 (x: Tensor) = 
        let y = DiffSharp.tensor [x.Item(0); x.Item(1); x.Item(2)]
        y.sum()

    let x = DiffSharp.tensor [2.1; 0.2; -1.1]
    printfn "fn1 grad at x = [2.1; 0.2; -1.1]: %A" (DiffSharp.grad fn1 x)
    printfn "fn2 grad at x = [2.1; 0.2; -1.1]: %A" (DiffSharp.grad fn2 x)
```

This code prints:
```
> fn1 grad at x = [2.1; 0.2; -1.1]: Tensor [1.000000, 1.000000, 1.000000]
> fn2 grad at x = [2.1; 0.2; -1.1]: Tensor 0.000000
```

Is this behaviour intended? If yes, how can I go around it if I need to reference elements in a similar way as above?

**Comment by gbaydin** [comment]
Hi @mgorinova the behavior you observed is by design. This is happening because the `DiffSharp.tensor` method is designed to create tensors from constant values and it's not a differentiable operation. 

This behavior is the same with PyTorch. For example

```python
import torch

def fn1(x):
    return x.sum()

def fn2(x):
    y = torch.tensor([x[0], x[1], x[2]])
    return y.sum()

x = torch.tensor([2.1,0.2,-1.1], requires_grad=True)

y = fn1(x)
y.backward()
print(x.grad)

y = fn2(x)
y.backward()
print(x.grad)
```

```
tensor([1., 1., 1.])
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by gbaydin** [comment]
A way of achieving the result you want is to use either `dsharp.cat` or `dsharp.stack`, which are differentiable operations that combine given tensors into a new tensor. For example, the following works:

```fsharp
let fn1 (x:Tensor) = 
    x.sum()

let fn2 (x: Tensor) = 
    let y = dsharp.stack [x.[0]; x.[1]; x.[2]]
    y.sum()

let x = dsharp.tensor [2.1; 0.2; -1.1]
printfn "fn1 grad at x = [2.1; 0.2; -1.1]: %A" (DiffSharp.grad fn1 x)
printfn "fn2 grad at x = [2.1; 0.2; -1.1]: %A" (DiffSharp.grad fn2 x)
```
```
fn1 grad at x = [2.1; 0.2; -1.1]: Tensor [1.000000, 1.000000, 1.000000]
fn2 grad at x = [2.1; 0.2; -1.1]: Tensor [1.000000, 1.000000, 1.000000]
```

**Comment by dsyme** [comment]
Ah yes! of course.

**Comment by mgorinova** [comment]
Ah, this makes sense! Just tried it and it seems to work fine :) Thanks!
