### ISSUE TITLE
Tangents are not being propagated through the relu and sigmoid activations.

### ISSUE THREAD

**Issue by mrakgr** [DiffSharp/DiffSharp#16]
static member ReLU (a:D) =
        let inline ff(a) = max 0.f a
        let inline fd(a) = D.ReLU(a)
        let inline df(cp, ap, at) = (1.f + D.Sign(ap)) / 2.f
        let inline r(a) = ReLU_D(a)
        D.Op_D_D (a, ff, fd, df, r)

    static member Sigmoid (a:D) =
        let inline ff(a) = 1.f / (1.f + exp -a)
        let inline fd(a) = D.Sigmoid(a)
        let inline df(cp:D, ap, at) = cp * (1.f - cp)
        let inline r(a) = Sigmoid_D(a)
        D.Op_D_D (a, ff, fd, df, r)

In the `df` functions there should be an `at` in there somewhere. The DV and DM versions are similarly affected.

**Comment by gbaydin** [comment]
Yes, this looks like a bug. Thank you very much for reporting it.

**Comment by gbaydin** [comment]
This is fixed in version 0.7.7
