### ISSUE TITLE
DM and DV binary operations are not defined in Interop module.

### ISSUE THREAD

**Issue by zgrkpnr** [DiffSharp/DiffSharp#18]
For instance DM \* DM is definet, DV \* DV is also defined. But Matrix and Vector operations such as DM \* DV is not defined.

**Comment by smoothdeveloper** [comment]
@zgrkpnr could you provide a sample F# code which would do what you want from user perspective?

It is nice if the script has checks on the results of those operations so it can be converted to a test and the library implemented according to that spec.

**Comment by dsyme** [comment]
@zgrkpnr I pushed a fix for this.

BTW would you be interested in helping with admin, testing and future development on this project ?  It is an enjoyable codebase to work on!
