### ISSUE TITLE
duplicate implementation of AD.Float32 and AD.Float64

### ISSUE THREAD

**Issue by smoothdeveloper** [DiffSharp/DiffSharp#20]
I was looking at implementation files `AD.Float32.fs` and `AD.Float64.fs` and was thinking I could contribute a refactoring so the code is 100% identical but a dozen of lines at the top of each file.

It would basically consist of defining type alias and few literals. I think it would make extending and maintaining the library easier than it is now.

Does that sound like a good idea?

**Comment by smoothdeveloper** [comment]
Note that it would compile to exactly the same thing.

**Comment by dsyme** [comment]
Making the code identical sounds good

**Comment by smoothdeveloper** [comment]
@dsyme thanks I'll contribute a PR to that aim then.

**Comment by smoothdeveloper** [comment]
@dsyme / @gbaydin I've put a first commit in PR #20 it changes the AD.Float32 module and wonder if you could look at the diff and confirm all the naming is OK to proceed with AD.Float64.

Also, could we get #19 merged, it adds running the tests in our AppVeyor integration which are currently not running in master. master also doesn't build the tests for me which I think I've fixed in my paket PR.

**Comment by smoothdeveloper** [comment]
I've completed the same in AD.Float64, files look the same now besides the few aliases at the top.

**Comment by dsyme** [comment]
@smoothdeveloper Please feel free to contribute further alignments
