### ISSUE TITLE
Add .contiguous

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#200]
See https://pytorch.org/docs/stable/tensors.html#torch.Tensor.contiguous

Returns a contiguous in memory tensor containing the same data as self tensor. If self tensor is already in the specified memory format, this function returns the self tensor.

Parameters

memory_format (torch.memory_format, optional) – the desired memory format of returned Tensor. Default: torch.contiguous_format.

**Comment by dsyme** [comment]
Hmmm ok

Yes, that would be exactly the situation.  I guess we can assess when we need to.  

It might be good to map through the Torch operation nevertheless, at least up to raw tensors, just in case it is useful to workaround such a problem.

**Comment by gbaydin** [comment]
Ok, agreed! 

I think another related subject is implementing strided views in the reference backend if we do it at some point.
