### ISSUE TITLE
Run samples cleanly on GPU with one line addition

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#204]
@gbaydin I'm just wondering what your expectation/desire is here for the programming model

I'm looking at the VAE.fsx sample and trying to run it on GPU. Is the intent that I do this by setting GPU as the default device?

    dsharp.config(backend=Backend.Torch, device=Device.GPU)

or is it expected to instruct things via `model.move(Device.GPU)`?  In which case how do we specify the move of the data and related tensors to the GPU? 

When I make the GPU the default then  "Saving samples" takes a very long time. Adding this helps:

    samples.move(Device.CPU).saveImage(sprintf "samples_%A_%A.png" epoch i)

We should probably always move to the CPU before doing things like saveImage

**Comment by dsyme** [comment]
As an aside, to do GPU work using F# Interactive scripting on Windows using `dotnet fsi` I ndid the following

* Created DiffSharp.Tests.Gpu that has 

       <DIFFSHARP_TESTGPU>true</DIFFSHARP_TESTGPU>

* Used the following

```
#I "../tests/DiffSharp.Tests.Gpu/bin/Debug/netcoreapp3.0"
#r "TorchSharp.dll"
#r "DiffSharp.Core.dll"
#r "DiffSharp.Backends.Torch.dll"
System.Runtime.InteropServices.NativeLibrary.Load(@"E:\GitHub\dsyme\DiffSharp\tests\DiffSharp.Tests.Gpu\bin\Debug\netcoreapp3.0\runtimes\win-x64\native\torch_cuda.dll")
System.Runtime.InteropServices.NativeLibrary.Load(@"E:\GitHub\dsyme\DiffSharp\tests\DiffSharp.Tests.Gpu\bin\Debug\netcoreapp3.0\runtimes\win-x64\native\nvrtc-builtins64_102.dll")
System.Runtime.InteropServices.NativeLibrary.Load(@"E:\GitHub\dsyme\DiffSharp\tests\DiffSharp.Tests.Gpu\bin\Debug\netcoreapp3.0\runtimes\win-x64\native\caffe2_nvrtc.dll")
System.Runtime.InteropServices.NativeLibrary.Load(@"E:\GitHub\dsyme\DiffSharp\tests\DiffSharp.Tests.Gpu\bin\Debug\netcoreapp3.0\runtimes\win-x64\native\nvrtc64_102_0.dll")
```

**Comment by gbaydin** [comment]
I'm currently redesigning the dataset api and the NN related things. I have a couple of ideas that should take care of this issue.

**Comment by gbaydin** [comment]
> As an aside, to do GPU work using F# Interactive scripting on Windows using `dotnet fsi` I ndid the following
> 
> * Created DiffSharp.Tests.Gpu that has
>   ```
>    <DIFFSHARP_TESTGPU>true</DIFFSHARP_TESTGPU>
>   ```
> * Used the following
> 
> ```
> #I "../tests/DiffSharp.Tests.Gpu/bin/Debug/netcoreapp3.0"
> #r "TorchSharp.dll"
> #r "DiffSharp.Core.dll"
> #r "DiffSharp.Backends.Torch.dll"
> System.Runtime.InteropServices.NativeLibrary.Load(@"E:\GitHub\dsyme\DiffSharp\tests\DiffSharp.Tests.Gpu\bin\Debug\netcoreapp3.0\runtimes\win-x64\native\torch_cuda.dll")
> System.Runtime.InteropServices.NativeLibrary.Load(@"E:\GitHub\dsyme\DiffSharp\tests\DiffSharp.Tests.Gpu\bin\Debug\netcoreapp3.0\runtimes\win-x64\native\nvrtc-builtins64_102.dll")
> System.Runtime.InteropServices.NativeLibrary.Load(@"E:\GitHub\dsyme\DiffSharp\tests\DiffSharp.Tests.Gpu\bin\Debug\netcoreapp3.0\runtimes\win-x64\native\caffe2_nvrtc.dll")
> System.Runtime.InteropServices.NativeLibrary.Load(@"E:\GitHub\dsyme\DiffSharp\tests\DiffSharp.Tests.Gpu\bin\Debug\netcoreapp3.0\runtimes\win-x64\native\nvrtc64_102_0.dll")
> ```

About this, will this situation be simplified when DiffSharp 1.0 is released on nuget? I mean, can the user simply do a couple of #r nuget lines and be good to go without the System.Runtime.InteropServices.NativeLibrary.Load?

**Comment by gbaydin** [comment]
I think it's likely that the DiffSharp model should be just adding the `dsharp.config(backend=Backend.Torch, device=Device.GPU)` in the beginning and forgetting about the devices for the rest of the code (e.g., not need any model.move) unless one does some hybrid complex code that involves cpu and gpu tensors at the same time. I really care about these issues and I will share the setup I have in mind very soon.

**Comment by gbaydin** [comment]
About the `samples.move(Device.CPU).saveImage` example, this is a good observation. I think we should internally do a `.move(Device.CPU)` in `saveImage` by default. The saveImage code is currently a placeholder / first implementation to debug and inspect NN behavior. It's getting there. :)

**Comment by dsyme** [comment]
> I think we should internally do a .move(Device.CPU) within saveImage function by default. 

Yup

**Comment by dsyme** [comment]
@gbaydin Just to mention that VAE is about 3x slower using GPU as the default on my machine.  It could be data transfers, or it could be doing too many micro-operations on GPU

Would be good to get a python/torch baseline to compare against

**Comment by gbaydin** [comment]
I agree that we should have pytorch baselines for all the examples. I will work on that.

In the meantime, do you mean the GPU execution with the current vae.fsx is 3x slower than CPU? It would be good to profile it. One thing to note is that the model is quite small (maybe too small to benefit from GPU) and it doesn't have convolutional layers. We can have a larger-scale version of it with conv-deconv encoder-decoders.

**Comment by dsyme** [comment]
Here's a link to the changes I was using, including the DiffSharp.Tests.Gpu project that prepares an application ready to run with GPU binaries all in the right places, the the explicit loading workarounds are still required for F# Interactive

https://github.com/DiffSharp/DiffSharp/compare/dev...dsyme:gpu2?expand=1

**Comment by gbaydin** [comment]
@dsyme in #377 I worked on improving GPU usage based on your observations in this issue. I also went through all data loading code to ensure that things are loaded to CPU/RAM by datasets and then moved over to GPU by the dataloader (this is consistent with typical PyTorch usage as well). 

With the code you used to get the numbers you reported above, I currently get the following:

CPU (6 core, i7-4960X CPU @ 3.60GHz)
```
mean trainLoader.epoch(): tensor(0.0459449) seconds
mean reverseDiff(): tensor(0.000353972) seconds
mean model.loss(): tensor(0.0597183) seconds
mean l.reverse(): tensor(0.359975) seconds
mean optimizer.step: tensor(0.0105088) seconds
Real: 00:00:15.373, CPU: 00:00:37.100, GC gen0: 113, gen1: 47, gen2: 2
```

GPU (TITAN Xp)
```
mean trainLoader.epoch(): tensor(0.0477155) seconds
mean reverseDiff(): tensor(0.000194097) seconds
mean model.loss(): tensor(0.00695044) seconds
mean l.reverse(): tensor(0.486765) seconds
mean optimizer.step: tensor(0.0090217) seconds
Real: 00:00:19.571, CPU: 00:00:21.310, GC gen0: 113, gen1: 46, gen2: 2
```

Thinking this is a case where we have small VAE with linear-only layers where multithreaded CPU libtorch is good enough and we don't benefit from GPU, I implemented a convolutional VAE as follows.

```fsharp
open System
open DiffSharp
open DiffSharp.Compose
open DiffSharp.Model
open DiffSharp.Optim
open DiffSharp.Data

dsharp.config(backend=Backend.Torch, device=Device.GPU)
dsharp.seed(0)

let urls = ["https://ossci-datasets.s3.amazonaws.com/mnist/train-images-idx3-ubyte.gz";
            "https://ossci-datasets.s3.amazonaws.com/mnist/train-labels-idx1-ubyte.gz";
            "https://ossci-datasets.s3.amazonaws.com/mnist/t10k-images-idx3-ubyte.gz";
            "https://ossci-datasets.s3.amazonaws.com/mnist/t10k-labels-idx1-ubyte.gz"]

let trainSet = MNIST("../data", urls=urls, train=true, transform=id)
let trainLoader = trainSet.loader(batchSize=256, shuffle=true)

let encoder =
    Conv2d(1, 32, 4, 2)
    --> dsharp.relu
    --> Conv2d(32, 64, 4, 2)
    --> dsharp.relu
    --> Conv2d(64, 128, 4, 2)
    --> dsharp.flatten(1)

let decoder =
    dsharp.unflatten(1, [128;1;1])
    --> ConvTranspose2d(128, 64, 4, 2)
    --> dsharp.relu
    --> ConvTranspose2d(64, 32, 4, 3)
    --> dsharp.relu
    --> ConvTranspose2d(32, 1, 4, 2)
    --> dsharp.sigmoid

let model = VAE([1;28;28], 64, encoder, decoder)
let optimizer = Adam(model, lr=dsharp.tensor(0.001))

let ttrainLoaderEpoch = Array.zeroCreate<float> (trainLoader.length)
let treverseDiff = Array.zeroCreate<float> (trainLoader.length)
let tmodelLoss = Array.zeroCreate<float> (trainLoader.length)
let treverse = Array.zeroCreate<float> (trainLoader.length)
let toptimizerStep = Array.zeroCreate<float> (trainLoader.length)

let epochs = 0
for epoch = 0 to epochs do
    let t = Diagnostics.Stopwatch()
    t.Start()
    let mutable tlast = t.Elapsed
    for i, x, _ in trainLoader.epoch() do
        ttrainLoaderEpoch.[i] <- (t.Elapsed - tlast).TotalSeconds
        tlast <- t.Elapsed
        model.reverseDiff()
        treverseDiff.[i] <- (t.Elapsed - tlast).TotalSeconds
        tlast <- t.Elapsed
        let l = model.loss(x)
        tmodelLoss.[i] <- (t.Elapsed - tlast).TotalSeconds
        tlast <- t.Elapsed
        l.reverse()
        treverse.[i] <- (t.Elapsed - tlast).TotalSeconds
        tlast <- t.Elapsed
        optimizer.step()
        toptimizerStep.[i] <- (t.Elapsed - tlast).TotalSeconds
        tlast <- t.Elapsed
        if i % 100 = 0 then
            printfn "epoch: %A/%A minibatch: %A/%A loss: %A time: %A" epoch epochs i trainLoader.length (float(l)) t.Elapsed

printfn "mean trainLoader.epoch(): %A seconds" (ttrainLoaderEpoch |> dsharp.tensor |> dsharp.mean)
printfn "mean reverseDiff(): %A seconds" (treverseDiff |> dsharp.tensor |> dsharp.mean)
printfn "mean model.loss(): %A seconds" (tmodelLoss |> dsharp.tensor |> dsharp.mean)
printfn "mean l.reverse(): %A seconds" (treverse |> dsharp.tensor |> dsharp.mean)
printfn "mean optimizer.step: %A seconds" (toptimizerStep |> dsharp.tensor |> dsharp.mean)
```

With this I get the following timings.

CPU (6 core, i7-4960X CPU @ 3.60GHz)
```
mean trainLoader.epoch(): tensor(0.00557258) seconds
mean reverseDiff(): tensor(0.000133714) seconds
mean model.loss(): tensor(0.0663529) seconds
mean l.reverse(): tensor(0.197393) seconds
mean optimizer.step: tensor(0.00768008) seconds
Real: 00:01:06.355, CPU: 00:05:25.230, GC gen0: 160, gen1: 78, gen2: 2
```

GPU (TITAN Xp)
```
mean trainLoader.epoch(): tensor(0.00582527) seconds
mean reverseDiff(): tensor(0.000149021) seconds
mean model.loss(): tensor(0.0105418) seconds
mean l.reverse(): tensor(0.0906422) seconds
mean optimizer.step: tensor(0.00936328) seconds
Real: 00:00:30.843, CPU: 00:00:33.390, GC gen0: 160, gen1: 78, gen2: 2
```

**Comment by gbaydin** [comment]
I'm closing this as addressed.
