### ISSUE TITLE
TestTensorConvTranspose1D and 2D failures on Windows with Torch/GPU

### ISSUE THREAD

**Issue by VisualMelon** [DiffSharp/DiffSharp#211]
The tests TestTensorConvTranspose1D and TestTensorConvTranspose2D are both failing under Windows on GPU (but not under CPU). The failures are on the last assertion in each test. I have no idea why they are failing... the values don't look ridiculous, and the dtypes are fine. Here are some sign-posts:
 - 1D, 2D fail in b93f383 (and 3D, but for different reasons)
 - 2D fails in 9022cf7c (no 1D)
 - 2D passes in 542bdcc (no 1D)

I'll take another look at this soon, but thought I'd better share the confusion sooner than later. Shout if you want me to test anything.

**Comment by dsyme** [comment]
Thanks for this

**Comment by VisualMelon** [comment]
Had another look at this with the 1.7 update. The issue seems to be some non-zero negative values in the actual values: note that the signs for all the -0.0 values are -1. The zeros in the correct values then compare as different in `allclose`. Outputs in `TestTensorConvTranspose1D`:

```
 t3s3p6d3Correct:
 tensor([[[4.044300, 0.000000, 0.000000, -2.559300, 0.000000, 0.000000, -0.249300, 0.000000, 0.000000, 3.548400],
          [0.150400, 0.000000, 0.000000, -3.700200, 0.000000, 0.000000, -1.831400, 0.000000, 0.000000, 1.105800]]],device=cuda0,backend=Torch)
 t3s3p6d3Correct.sign():
 tensor([[[1.000000, 0.000000, 0.000000, -1.000000, 0.000000, 0.000000, -1.000000, 0.000000, 0.000000, 1.000000],
          [1.000000, 0.000000, 0.000000, -1.000000, 0.000000, 0.000000, -1.000000, 0.000000, 0.000000, 1.000000]]],device=cuda0,backend=Torch)
 t3s3p6d3:
 tensor([[[4.044492, -0.000000, 0.000000, -2.559461, 0.000000, -0.000000, -0.249173, -0.000000, -0.000000, 3.548475],
          [0.150388, -0.000000, -0.000000, -3.700144, -0.000000, -0.000000, -1.831483, -0.000000, -0.000000, 1.105857]]],device=cuda0,backend=Torch)
 t3s3p6d3.sign():
 tensor([[[1.000000, -1.000000, 1.000000, -1.000000, 1.000000, -1.000000, -1.000000, -1.000000, -1.000000, 1.000000],
          [1.000000, -1.000000, -1.000000, -1.000000, -1.000000, -1.000000, -1.000000, -1.000000, -1.000000, 1.000000]]],device=cuda0,backend=Torch)
```

It's a similar picture in TestTensorConvTranspose2D.

**Comment by dsyme** [comment]
I've fixed these, the tests were testing for a relative tolerance only, but for numbers very very close to zero this was not enough, so I added an absolute tolerance.  

https://github.com/DiffSharp/DiffSharp/pull/242/files#diff-260ff92a817daa55ad2b874e084c92d688bbfafc4629d9784bb328d88b8e0b81R6225

**Comment by VisualMelon** [comment]
Can confirm all test passing under Windows with Torch/GPU now.
