### ISSUE TITLE
LayerNorm3D operation needed for BERT model

### ISSUE THREAD

**Issue by moloneymb** [DiffSharp/DiffSharp#214]
You're going to need this Op as part of doing a BERT model.

Layer Norm https://arxiv.org/abs/1607.06450

Tensorflow https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/contrib/layers/python/layers/layers.py#L2204

F# Tensorflow https://github.com/moloneymb/BERTInFSharp/blob/7c9c51239b0e34ad41bfce8d3b5239ec00b75d23/BertInFSharp/utils.fs#L631

**Comment by dsyme** [comment]
Tracking this in https://github.com/DiffSharp/DiffSharp/issues/227
