### ISSUE TITLE
OpenBLAS x86 also works with DiffSharp

### ISSUE THREAD

**Issue by zgrkpnr** [DiffSharp/DiffSharp#22]
I have tried using native providers' x86 builds and used "Any CPU" as build configuration. It builds and runs.

I have testes vector and matrix multiplication, transpose etc. 
gradient and hessian also works. 

I obtained x86 builds of native providers from MathNet distribution. They have both x64 and x86 providers.

**Comment by smoothdeveloper** [comment]
@zgrkpnr what are the changes in code you had to make if it doesn't work as is currently?

**Comment by dsyme** [comment]
@zgrkpnr This is great to know.  We should document this and also enable 32-bit testing on Mono OSX
