### ISSUE TITLE
Question: Tensor.matmul

### ISSUE THREAD

**Issue by migueldeicaza** [DiffSharp/DiffSharp#228]
Tensor.matmul is currently tied to matrices and unlike PyTorch does not attempt to turn a vector into a matrix suitable to be operated on.   Is this the intended design, or just a temporary limitation?

This is matmul as defined in PyTorch:

https://pytorch.org/docs/stable/generated/torch.matmul.html

**Comment by dsyme** [comment]
See #88 , yet to be integrated

**Comment by dsyme** [comment]
Closed as this is now in
