### ISSUE TITLE
Missing some operations on vectors/matrices C#

### ISSUE THREAD

**Issue by Zerseu** [DiffSharp/DiffSharp#23]
Hello,

I am unable to find the following operations on vectors and matrices when coding in C#:

let v = v1 &\* v2 // Vector outer (dyadic, tensor) product
let v = v1 .\* v2 // Element-wise (Hadamard) product
let v = v1 ./ v2 // Element-wise division
let v = v1 *\* v2 // Element-wise exponentiation

And:

let m  = m1 .\* m2 // Element-wise (Hadamard) product
let m  = m1 ./ m2 // Element-wise division
let m  = m1 *\* m2 // Element-wise exponentiation

Thank you.

**Comment by dsyme** [comment]
@Zerseu This is because those operators aren't available in the C# language. https://github.com/DiffSharp/DiffSharp/issues/37 pushes a fix where you can do

```fsharp
DV.PointwiseMultiply(a,b)
DV.PointwiseDivision(a,b)
DV.Pow(a,b)
DV.TensorMultiply(a,b)

DM.PointwiseMultiply(a,b)
DM.PointwiseDivision(a,b)
DM.Pow(a,b)
```

Please send a PR if you would like to change the names if you can identify more standard names in other math libraries
