### ISSUE TITLE
Optional parameters and C# API

### ISSUE THREAD

**Issue by kevmal** [DiffSharp/DiffSharp#233]
@dsyme Was listening to the ML Community Standup, you mentioned most likely needing a C# wrapper due to optional parameters... I personally don't care about C# support but couldn't the F# optional parameters just be tagged with `[<Optional>]`? Since null = None and with `Option.op_Implicit` you'd get the expected experience from both C#/F#.

**Comment by dsyme** [comment]
> @dsyme Was listening to the ML Community Standup, you mentioned most likely needing a C# wrapper due to optional parameters... I personally don't care about C# support but couldn't the F# optional parameters just be tagged with [<Optional>]? Since null = None and with Option.op_Implicit you'd get the expected experience from both C#/F#.

I believe this is possible, but it still is awkward if you actually want to give values for the parameters

We will look into this in an iteration or two I believe

**Comment by kevmal** [comment]
Providing values is natural because of `Option.op_Implicit`. The worst part is the noisy intellisense

![image](https://user-images.githubusercontent.com/7281367/98853019-c2708800-2415-11eb-9e29-b4a2bb1f6efc.png)

**Comment by dsyme** [comment]
Yes that's noisy :-)
