### ISSUE TITLE
Any chance to have it working on Mac Os X? (re-enable for 32-bit?)

### ISSUE THREAD

**Issue by adicirstei** [DiffSharp/DiffSharp#24]
Hi,

I would love to use it on Mac OsX. Any idea what I should do?

currently I get

```
System.DllNotFoundException: libopenblas                                                                                          
  at (wrapper managed-to-native) DiffSharp.Backend.OpenBLAS+BLASExtensions:cblas_somatcopy
```

**Comment by smoothdeveloper** [comment]
@adicirstei can you check if your system has openblas installed?

I believe the nuget package of this project embeds the binaries for windows but it is expected on other platform for it to be installed system wide.

If you have this checked and it still doesn't work, it should be reasonably easy to patch the code pointing to the native library to make it work on mac computers.

**Comment by neverfox** [comment]
OS X comes with OpenBLAS, so I doubt it's an issue of it not being installed. In any case, I'd be interested in this too. @adicirstei I'm curious about the process you used to build the project, as I'm not having any luck with simply Visual Studio Code.

**Comment by dsyme** [comment]
@smoothdeveloper @neverfox @adicirstei  If you get a chance to try again on master the project should now build cleanly (see build.sh)  You will need a fairly recent OpenBlas and Mono OSX 64-bit

If you manage to get it to work on OSX 64-bit please drop a note here with any instructions needed
