### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by gafter** [DiffSharp/DiffSharp#247]
I can't find a license for DiffSharp. I found notes elsewhere saying "LGPL" but not here and no hint as to which version.

**Comment by gafter** [comment]
The reference for the LGPL license is (https://engineering.purdue.edu/~qobi/papers/ad2016c.pdf)

I also found a comment elsewhere that the license is BSD (https://libraries.io/github/DiffSharp/DiffSharp)

It would be nice to have clarity.

**Comment by gafter** [comment]
Slide 4 of this deck (http://www.autodiff.org/ad16/Oral/Baydin_Diffsharp.pdf) says MIT license.

**Comment by dsyme** [comment]
It's BSD, the relicensing was done here: https://github.com/DiffSharp/DiffSharp/commit/f88e387fe4d82464183c33c054080517511411bf

Will clarify

**Comment by gafter** [comment]
I somehow missed that.

**Comment by dsyme** [comment]
Totally understandable!  It should have been explicit in "dev" branch

**Comment by dsyme** [comment]
Ping my on Teams if you'd like to discuss DiffSharp in depth, happy to take you on a tour of where we're at
