### ISSUE TITLE
Tensor printing considerations

### ISSUE THREAD

**Issue by gbaydin** [DiffSharp/DiffSharp#259]
@dsyme about the change merged here #234 
```
tensor([[.... data ]],dtype=Float32,device=cuda:2,backend=Torch)
```
I have two things I would like to think about:

1. I think it would be good to consider a few things like if we can make the printed version valid DiffSharp code. In other words, copying the printed tensor string and pasting it into a code file (or dotnet interactive) could instantiate a copy of the tensor. This type of thing is really good to have in practice. Would it be too verbose if we did this?

2. Minor: I wouldn't mind having `Tensor` instead of `tensor` here. But for the copy--paste thing to work, `tensor` can make more sense, it could just work with a `dsharp.` prefix to instantiate new tensors like `dsharp.tensor(...)`.

**Comment by cgravill** [comment]
1. sounds good, we did something similar on another project and being able to easily copy and paste values into other programs was very convenient.

**Comment by dsyme** [comment]
Cut and paste does make sense though may be a bit verbose.  

I think lower case `tensor` looks better for both the copy-paste reason and the similarity with outputs from Torch (which look good I think)

**Comment by gbaydin** [comment]
Closing as the latest printing code behaves sufficiently well in addressing these comments.
