### ISSUE TITLE
split missing dim

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#265]
I just spotted that this code

        | TensorF(ap,ad,at) -> Array.map2 (fun p d -> TensorF(p,d,at)) (ap.split(sizes)) (ad.split(sizes, dim=dim))

should be

        | TensorF(ap,ad,at) -> Array.map2 (fun p d -> TensorF(p,d,at)) (ap.split(sizes, dim=dim)) (ad.split(sizes, dim=dim))

Adding this issue to track this

**Comment by gbaydin** [comment]
Fixed in #367, thank you!
