### ISSUE TITLE
Model.forward with multiple inputs

### ISSUE THREAD

**Issue by pkese** [DiffSharp/DiffSharp#270]
It seems that there is no way to write models with multiple input tensors, like:
- two images of different size
- data + data specific encoding or lookup table
- data + initial values of latent variables

The problem is that Model.forward is defined with a just single tensor
```fsharp
type Model() =
    abstract member forward: Tensor -> Tensor
```
Is there any workaround for that?

**Comment by dsyme** [comment]
See #248, not yet integrated

However note the Model framework is very thin, so if you're experienced at F# it's fairly simple to define it in your own code and can lead to interesting innovations

**Comment by gbaydin** [comment]
@pkese thank you for this suggestion. The generic model implementation in #248 got recently merged and now one can freely define the input and output types of models.

The use case you were referring to can be implemented as follows:

```fsharp
type GenericModelExample() =
    inherit Model<(Tensor*Tensor),Tensor>()
    override __.forward((x, y)) = // Tensor * Tensor -> Tensor
```

This is quite powerful and you can basically implement models of any type. The following is a test case from: https://github.com/DiffSharp/DiffSharp/blob/be2104cce6fd2091a73127bf237fdf28d227f45a/tests/DiffSharp.Tests/TestModel.fs#L52

```fsharp
type GenericModelIntString() =
    inherit Model<int,string>()
    let fc1 = Linear(1, 2)
    let fc2 = Linear(2, 1)
    do base.add([fc1; fc2], ["fc1"; "fc2"])
    do base.init (fun (_, t) -> t.onesLike())
    override __.forward(x) =
        x |> dsharp.tensor
        |> dsharp.view([1; -1])
        |> fc1.forward
        |> fc2.forward
        |> int
        |> string
```

I expect to write lots of `<string, string>` models for things like translation between languages etc. which is quite exciting.
