### ISSUE TITLE
CI failing due to MNIST download, test disabled

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#289]
The MNIST download is failing in CI automation

**Comment by dsyme** [comment]
The test was disabled here: https://github.com/DiffSharp/DiffSharp/pull/290

**Comment by gbaydin** [comment]
That's bad news. It's been working fine in CI for many months.

I wasn't able to locate a CI run where this failed. Can you please point me to it so I can inspect?

**Comment by gbaydin** [comment]
Just to note here that this is a general problem with Yann LeCun's website affecting everyone. See for example https://discuss.pytorch.org/t/mnist-server-down/114433/16

I think the website served the community well all these years but probably it's reaching its limits.
