### ISSUE TITLE
Bug in Adam state step

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#292]
This line is a bug, it is incrementing stateStep every time the updateRule is called, for each parameter.

https://github.com/DiffSharp/DiffSharp/blob/dev/src/DiffSharp.Core/Optim.fs#L84

It should only be incremented once per iteration, not once per each parameter update.

This is important because we exponentiate by stateStep here: https://github.com/DiffSharp/DiffSharp/blob/dev/src/DiffSharp.Core/Optim.fs#L89

**Comment by gbaydin** [comment]
This is actually important, thanks for catching it!
