### ISSUE TITLE
dsharp.devices() with no backend assumes reference backend, doesn't report CUDA

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#304]
From https://github.com/DiffSharp/DiffSharp/issues/303

`dsharp.devices()` with no backend assumes reference backend, doesn't report CUDA 

Possible solutions

1. default to Backend.Torch if available ; OR

2. require a backend argument to `dsharp.devices()` OR

3. have `dsharp.devices()` iterate all available backends and have Device objects report the backend

Probably the simplest user experience is (1) - we change the entire notion of "Backend.Default" to proactively probe for the Torch backend.  The problem however is how often to do this - the dynamic addition of package references via `#r ...` means that the Torch backend may suddenly become available.  We could do it on first call, that is likely enough TBH.

**Comment by dsyme** [comment]
From https://github.com/DiffSharp/DiffSharp/issues/303

`dsharp.devices()` with no backend assumes reference backend, doesn't report CUDA 

Possible solutions

1. default to Backend.Torch if available ; OR

2. require a backend argument to `dsharp.devices()` OR

3. have `dsharp.devices()` iterate all available backends and have Device objects report the backend

Probably the simplest user experience is (1) - we change the entire notion of "Backend.Default" to proactively probe for the Torch backend.  The problem however is how often to do this - the dynamic addition of package references via `#r ...` means that the Torch backend may suddenly become available.  We could do it on first call, that is likely enough TBH.

**Comment by gbaydin** [comment]
Option (1) sounds good, but it brings the question of which backend should be the default if/when more backends are introduced in the future. There could be a priority backend list that are tested one by one (like a boot devices order). I'm also afraid (without much evidence) that the assembly finding code is a bit hacky and can break the whole library at some point in a future dotnet version. https://github.com/DiffSharp/DiffSharp/blob/7e921c298c3402278eb8ddfd6d993abc85e6adfe/src/DiffSharp.Core/Backend.fs#L62

Option (3) is a more conservative approach, contained to how we implement `dsharp.devices()`. I like this one actually because it feels safer.

**Comment by dsyme** [comment]
Ok

**Comment by gbaydin** [comment]
@dsyme in #378 I ended up implementing a solution similar to number (3) above.

The API looks like the following:
```fsharp
dsharp.backends // unit -> list<Backend>
dsharp.devices // option<Backend> * option<DeviceType> -> list<Device>
dsharp.backendsAndDevices // unit -> list<Backend * list<Device>>
dsharp.isBackendAvailable // Backend -> bool
dsharp.isDeviceAvailable // Device * option<Backend> -> bool
dsharp.isDeviceTypeAvailable // DeviceType * option<Backend> -> bool
dsharp.isCudaAvailable // option<Backend> -> bool
```

For example
```fsharp
printfn "%A" (dsharp.backends())
printfn "%A" (dsharp.backendsAndDevices())
printfn "%A" (dsharp.devices(Backend.Torch))
```
```
[Reference; Torch]
[(Reference, [Device (CPU, -1)]); (Torch, [Device (CPU, -1); Device (CUDA, 0)])]
[Device (CPU, -1); Device (CUDA, 0)]
```

I'm happy about this and not sure if we should also add the "default to Backend.Torch if available" behavior.

**Comment by gbaydin** [comment]
Merging #378 and closing this now :)
