### ISSUE TITLE
Update examples in C#

### ISSUE THREAD

**Issue by edxu96** [DiffSharp/DiffSharp#365]
Hi, thanks for this amazing tool, though I'm still struggling for how to use it in C#.

I'm developing VB/C# software for simulation of gas transportation. I'm planning to use `DiffSharp` to obtain derivatives (Jacobian matrix) of some nonlinear equations (like `public static double Calculate(double x, double y)`), so that I don't have to linearise them myself.

I think the previous tutorial on how to use in C# (https://diffsharp.github.io/DiffSharp/csharp.html) is very helpful, but it is not updated. I'm wondering if someone can give some hints regarding version 1.0.

**Comment by dsyme** [comment]
Our recommendation for now is just to use it from F#, and if necessary write an F# class of yours to call from C#.

We might eventually rejig to be fully ergonomic from C# but it's not on the v1.0 roadmap.

**Comment by edxu96** [comment]
Thanks for the quick reply. Will do it in that way.

Also, I find that for .NET Framework 4.6, the latest version is 0.7.7 (or prerelease 0.8.x) ;-) Will play around with that as well.

**Comment by dsyme** [comment]
> Also, I find that for .NET Framework 4.6, the latest version is 0.7.7 (or prerelease 0.8.x) ;-) Will play around with that as well.

This project will only support .NET Core 5.0 and later going forward (partly because that's what TorchSharp requires). Please use that.
