### ISSUE TITLE
Types for functions activations used in Sequential?

### ISSUE THREAD

**Issue by nhirschey** [DiffSharp/DiffSharp#397]
Is there interest in a pull request adding a few model layers representing activations for use in Sequential models? Many Pytorch examples use sequential, and this could be helpful for beginners trying to translate pytorch models to diffsharp.

I recognize that you may not want this because it increases the maintenance burden and `-->` covers many `Sequential` use cases. Hence the question.

For example, the pytorch.org [quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html#creating-models) model definition example uses sequential, and I believe this is the correct translation:

```fsharp
type ReLU() =
    inherit Model()
    override _.ToString() = sprintf "ReLU()"
    override m.forward(value) = 
        dsharp.relu(value)

type Flatten(?startDim:int,?endDim:int) =
    inherit Model()
    let startDim = defaultArg startDim 1
    override _.ToString() = sprintf "Flatten()"
    override m.forward(value) =
        dsharp.flatten(value, startDim, ?endDim=endDim) 
        
type NeuralNetwork() =
    inherit Model()
    let linear_relu_stack = Sequential([
        Linear(28*28, 512)
        ReLU()
        Linear(512, 512)
        ReLU()
        Linear(512, 10)
    ])
    do base.addModel([linear_relu_stack])
    member self.flatten = Flatten()
    
    override self.forward(x) =
        let x = self.flatten.forward(x)
        let logits = linear_relu_stack.forward(x)
        logits


let model = NeuralNetwork()
```

**Comment by gbaydin** [comment]
Hi @nhirschey thank you for this suggestion. 

I'm thinking that introducing `Model` wrapper types around functions is not a good direction for DiffSharp or even for PyTorch. The reason they exist in PyTorch is historical, as far as I know: the `Sequential` and PyTorch module wrappers for simple functions are from the old Torch days when things were composed of coarse-grained neural network modules. When PyTorch introduced general-purpose autodiff, I remember PyTorch devs actually advising against using older containers like `Sequential`, `Parallel` etc.

**Comment by gbaydin** [comment]
I looked at a few ways of implementing the same model you shared above.

```fsharp
open DiffSharp.Compose

type NeuralNetwork2() =
    inherit Model()
    let fc1 = Linear(28*28, 512)
    let fc2 = Linear(512, 512)
    let fc3 = Linear(512, 10)
    do base.addModel([fc1; fc2; fc3])

    override _.forward(x) =
        x |> dsharp.flatten(1)
        |> fc1.forward |> dsharp.relu
        |> fc2.forward |> dsharp.relu
        |> fc3.forward

let model2 = NeuralNetwork2()
```

```fsharp
// Instantiate and compose at the same time
let model3 = 
    dsharp.flatten(1)
    --> Linear(28*28, 512)
    --> dsharp.relu
    --> Linear(512, 512)
    --> dsharp.relu
    --> Linear(512, 10)
```

`model2` and `model3` would do exactly the same job with `model` above. Personally `model3` is my favorite while `model2` would look more familiar to people with PyTorch experience.

**Comment by gbaydin** [comment]
However, I think there is no harm in introducing a generic function-to-model wrapper that can be constructed around by basically any function. Something like the following:

```fsharp
let model4 = Sequential([
    Model(dsharp.flatten(1))
    Linear(28*28, 512)
    Model(dsharp.relu)
    Linear(512, 512)
    Model(dsharp.relu)
    Linear(512, 10)
])
```

What do you think?

**Comment by gbaydin** [comment]
Wrote a little PR about this here: #418

**Comment by nhirschey** [comment]
Thank you for the thoughtful response. I am not aware of Torch's history, so that is helpful. 

I prefer `model3` with `-->` syntax, but given how frequently I have seen `Sequential` in PyTorch examples, I think that your function-to-model wrapper is a worthy addition. It is an elegant solution.

This context may help explain my motivations. I want to be able to tell my students: 
> "Here's the PyTorch.org quickstart in Python. Here's the *literal* line by line translation using F# and Diffsharp. See, it's almost exactly the same. Now, look at the same model in DiffSharp `-->` style, isn't that simpler?"

I think there's value in having the ability to do a line-by-line translation of whatever PyTorch.org has as the quickstart, even if it is more common for people to use `-->` once they're familiar with the library.

**Comment by gbaydin** [comment]
@nhirschey I'm about to merge #418 which introduced a simple `Model(...)` constructor that can take any `Tensor->Tensor` function and return a model object wrapping it. This allows using the `model4` case in my previous message above.

It also allows something like the following

```fsharp
let ReLU() = Model(dsharp.relu)
let Flatten() = Model(dsharp.flatten)

type NeuralNetwork() =
    inherit Model()
    let linear_relu_stack = Sequential([
        Linear(28*28, 512)
        ReLU()
        Linear(512, 512)
        ReLU()
        Linear(512, 10)
    ])
    do base.addModel(linear_relu_stack)
    member self.flatten = Flatten()
    
    override self.forward(x) =
        let x = self.flatten.forward(x)
        let logits = linear_relu_stack.forward(x)
        logits

let model = NeuralNetwork()
```

which is a lighter version of your first example, with less boilerplate.

However, I understand that there is value in having some `Model` objects already in the library to cover the use case you described above. I think it would be fine to have a PR introducing these to the main library if you'd like.

**Comment by nhirschey** [comment]
Thank you for adding `Model(...)`. This looks fantastic and the two versions (`model 4` and `let ReLu() = Model(dsharp.relu)`) are sufficient to cover my use case.

I'll close this issue as addressed. With the addition of `Model(...)`, I no longer feel the need to submit a PR adding `Model` objects for activation functions.

Thanks again for this great library.
