### ISSUE TITLE
In rnn, buffer.nelement differences between newly created stateVector and saved stateVector cause `loadState` to fail

### ISSUE THREAD

**Issue by nhirschey** [DiffSharp/DiffSharp#422]
###  Summary
I don't think that saving and loading state is working properly for RNNs. For example in rnn.fsx, if I create languageModel from scratch there are no buffers, but restoring a previously saved stateVector tries to restore the prior model buffers. The `buffer.nelement` differences between the new model (w/o buffers) and the prior state (w/ buffers) causes an exception when trying to restore the old stateVector. 

I found a workaround saving and restoring "state" rather than "stateVector". Is using "state" preferable?

### Problem

If I run `rnn.fsx` as written, the script uses `languageModel.saveState` to save model state after each `validInterval`.
https://github.com/DiffSharp/DiffSharp/blob/4ab0e66c5b02e1c1c6956f2710ec9f1897fce6f0/examples/rnn.fsx#L89

If I close the session and start again it should reload that state into my model here:
https://github.com/DiffSharp/DiffSharp/blob/4ab0e66c5b02e1c1c6956f2710ec9f1897fce6f0/examples/rnn.fsx#L52

However, if I do that I get an error:
```fsharp
> languageModel.loadState(modelFileName)
System.Exception: Expecting tensors.nelement (855105) and ParameterDict.nelement (854081) to be the same
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at DiffSharp.Model.ParameterDict.unflatten(Tensor tensors)
   at DiffSharp.Model.ModelBase.loadState(String fileName)
   at <StartupCode$FSI_0003>.$FSI_0003.main@()
Stopped due to error
```

This error is caused by `buffer.nelement` differences and the fact that set with `stateVector`  uses `ParameterDict.unflatten` and `ParameterDict.unflatten` requires the new and old nelements to be the same.

For example, summary of a freshly created language model with no buffers:
```fsharp
val it: string =
  "---
Model                                              Params
---
RNNCell(65, 512)                                  295,936
RNNCell(512, 512)                                 524,800
Linear(512, 65)                                    33,345
---
Total params                  : 854,081
Trainable params              : 854,081
Non-trainable params (buffers): 0
---
Total params size (MiB)       : 3.26
---
"
```

Summary of fully restored model saved using `languageModel.save` (*not* saveState):
```fsharp
val it: string =
  "---
Model                                              Params
---
RNNCell(65, 512)                                  295,936
RNNCell(512, 512)                                 524,800
Linear(512, 65)                                    33,345
---
Total params                  : 855,105
Trainable params              : 854,081
Non-trainable params (buffers): 1,024
---
Total params size (MiB)       : 3.26
---
"
```

the buffers causing the problem are the RNNCell-hidden buffers.
```fsharp
> savedModel.state |> Seq.map (fun (a,b) -> a,b.value.nelement) |> Seq.toList
val it: (string * int) list =
  [("RNNCell-weight-ih__1", 33280); ("RNNCell-weight-hh__1", 262144);
   ("RNNCell-bias__1", 512); ("RNNCell-weight-ih__2", 262144);
   ("RNNCell-weight-hh__2", 262144); ("RNNCell-bias__2", 512);
   ("Linear-weight__1", 33280); ("Linear-bias__1", 65);
   ("RNNCell-hidden__1", 512); ("RNNCell-hidden__2", 512)]
```

The loadState problem comes from here is stateVector calling unflatten
https://github.com/DiffSharp/DiffSharp/blob/3072789fdfd577fe64071e1e35f8e4c280f757ec/src/DiffSharp.Core/Model.fs#L303

And the nelement requirement in unflatten.
https://github.com/DiffSharp/DiffSharp/blob/3072789fdfd577fe64071e1e35f8e4c280f757ec/src/DiffSharp.Core/Model.fs#L181 

### Workaround
This workaround for fully restoring the state might work? It bypasses the problematic `ParameterDict.unflatten` nelement check.

```fsharp
type ModelBase with
    member m.saveState2(fileName, ?noDiff:bool) =
        let noDiff = defaultArg noDiff true
        let ss =
            if noDiff then 
                let ss = m.state.copy()
                ss.noDiff()
                ss
            else m.state
        saveBinary ss fileName
    member m.loadState2(filename) =
        let s:ParameterDict = loadBinary filename
        // set failwith "keys are not the same" even though they're the same?
        // Is this a private/public code issue?
        // m.state.set(s)
        m.state.iter(fun (n,p) -> p.value <- s[n])
```

**Comment by gbaydin** [comment]
Thank you for reporting this with and for the investigation of the cause. I was able to reproduce the same problem and I'm working on the fix.

**Comment by gbaydin** [comment]
In #425 I improved the state saving and loading design that brings the API closer to PyTorch conventions. Also had to reimplement RNNs with a better design that doesn't keep hidden state as a buffer. This is also closer to PyTorch design.
