### ISSUE TITLE
Reference backend does not support from end index slicing

### ISSUE THREAD

**Issue by nhirschey** [DiffSharp/DiffSharp#431]
The torch backend supports from-end slicing using negative integer indices. This gives an error with the reference backend.

Reverse slicing works with the torch backend:
```fsharp
#r "nuget: DiffSharp-cpu,1.0.7"

open DiffSharp
open DiffSharp.Compose

let x = dsharp.tensor([0.0; 1.0; 2.0],backend=Backend.Torch)
x[-1] // tensor(2.,backend=Torch)
x[-2] // tensor(1.,backend=Torch)
```

It breaks with the reference backend.
```fsharp
let y = dsharp.tensor([0.0; 1.0],backend=Backend.Reference)
y[-1] 
(*
Error: System.Exception: index ([|-1|]) is not valid for shape ([|2|])
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at DiffSharp.ShapeModule.checkCanIndex(Int32[] shape, Int32[] index)
...
*)
```

**Comment by nhirschey** [comment]
This is already fixed in https://github.com/DiffSharp/DiffSharp/commit/936402a1cbc095789323e7b9f7b83639daab854a, it just hasn't made it's way to the nuget version yet.

**Comment by dsyme** [comment]
I'm not sure if/when @gbaydin plans to make further releases. I've emailed asking for clarity.
