### ISSUE TITLE
Implement DV for non-AD modules?

### ISSUE THREAD

**Issue by awf** [DiffSharp/DiffSharp#46]
I'm porting an autodiff benchmark to DiffSharp 0.7, see at https://github.com/awf/ADBench/blob/master/tools/DiffSharp/ba.fs#L80

I'm using the "DV" vectors, which is great, and cleans up the code, but I would like to switch between AD, Numerical, and Symbolic DiffSharp without rewriting the code.  It looks as if "DV" is implemented only in AD.Float{32,64}.  I can happily port it to Numerical.*, but that becomes a lot of code duplication -- is that the way we should do it?

No, of course I could try to write generic code, but that worsens my error messages, and I need a linear algebra library anyway, so I may as well use this particular set of method names.

**Comment by dsyme** [comment]
@awf Yes, I suppose porting these to Numerical makes sense, though it does increase the code duplication along another dimension.

If you do it, use 
```
type number = double
[<Struct>]
type D = D of number
[<Struct>]
type DV = DV of number[]
```
etc.

**Comment by dsyme** [comment]
Closing because this is out of date for DiffSHarp 1.x, which is currently planned to be AD only. We may revist
