### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cgravill** [DiffSharp/DiffSharp#52]
There hasn't been a release of https://www.nuget.org/packages/DiffSharp/ since 2015 and lots of useful changes have been made since. Are there any plans for a release? Blockers you'd like help with?

I was able to build from source so I can use DiffSharp with .NET Core but I'd really like to share the work with others who are unlikely to build manually.

**Comment by cgravill** [comment]
I've pushed up a pre-release version NuGet for testing: https://www.nuget.org/packages/DiffSharp/0.8.0-beta it'd be great to get any feedback if it works for others.

There have been some API changes since the last release. The documentation has been updated. Once it's fully released we should republish the documentation as well. By way of example:

```fsharp
//DiffSharp >= 0.8.0
let adjoints = computeAdjoints L

//DiffSharp <= 0.7.7
L |> reverseProp (D 1.)
```

and

```fsharp
//DiffSharp >= 0.8.0
let mats' = mats |> Array.map (fun x -> primal (x - eta * adjoints.[x]))

//DiffSharp <= 0.7.7
let mats' = mats |> Array.map (fun x -> primal (x - eta * x.A))
```

**Comment by cgravill** [comment]
There have been a few more minor releases up to: https://www.nuget.org/packages/DiffSharp/0.8.4-beta and we've now been able to train some interesting models.

**Comment by dsyme** [comment]
I am closing this as the focus is now on DiffSharp 1.0 improvements. There is a feed of packages from the CI server if you want to play around with those, or you can build your own from `dev`

@cgravill please do continue to update to 0.8.4 etc.

**Comment by cgravill** [comment]
Sounds good, we have a working stable version that we don't have any immediate need to update.

Very much interested in switching to the `dev` version when we get a chance - the `#r "nuget:` under F# 5.0 is brilliant to see:

https://github.com/DiffSharp/DiffSharp#using-ci-build-packages
