### ISSUE TITLE
Support more target frameworks in DiffSharp.fsproj

### ISSUE THREAD

**Issue by allisterb** [DiffSharp/DiffSharp#57]
Right now only the netstandard2.0 target framework is supported by the DiffSharp project file. This causes build failures in libraries that use DiffSharp and must support net45 and older .NET frameworks and toolchains. Both NET Standard 2.0 and other targets can be supported by using this line in DiffSharp.fsroj

`<TargetFrameworks>netstandard2.0;netcoreapp2.0;net45</TargetFrameworks>`

I built DiffSharp successfully for these targets without any changes to the source code and the tooling will take care of sorting out the dependencies and packaging the libraries correctly for NuGet.

**Comment by dsyme** [comment]
I think it's better for the project if it focuses on moving ahead and assumes .NET Standard 2.0 (or indeed .NET Standard 2.1 if it proves necessary)

Is there any reason you can't update to .NET 4.7.2, which supports .NET Standard 2.0 components?

**Comment by allisterb** [comment]
The main reason is I'd like to run my F# projects on Azure Notebooks which uses Mono 5.1 and I thought I should target the lowest .NET framework possible for safety and to minimize problems. I don't know if NuGet on Mono 5 can restore .NET Standard packages: https://stackoverflow.com/questions/53479603/reference-netstandard-nuget-package-in-4-7-2-project-mono

**Comment by dsyme** [comment]
@allisterb I see.  Yes, that F# implementation in Azure Notebooks should really be updated....

**Comment by dsyme** [comment]
@allisterb The thing is, we expect we will very soon get other .NET Standard 2.0 dependencies, e.g. if/when tensor support is added.

**Comment by dsyme** [comment]
Until then I guess we could add `net45` but please assume it's going away at some point...

**Comment by allisterb** [comment]
Actually I could just make my own fork and maintain the net45 target there. I may have to make a fork in any case because I'd like to integrate DiffSharp with my project and I might need access to the internals. So don't bother to add net45 unless there's more demand for it

**Comment by dsyme** [comment]
> Actually I could just make my own fork and maintain the net45 target there. I may have to make a fork in any case because I'd like to integrate DiffSharp with my project and I might need access to the internals. So don't bother to add net45 unless there's more demand for it

I think it's ok to add it for now, since it is easy and fits with the 0.8 release series.  But that might be the last series supporting it!

**Comment by allisterb** [comment]
ok cool, thanks!

**Comment by dsyme** [comment]
@allisterb COuld you send a PR for this?  thanks

**Comment by cgravill** [comment]
In case it helps, even with the current version of Mono on Azure Notebooks it is possible to use the .NET Standard version of DiffSharp:

![image](https://user-images.githubusercontent.com/1099725/63092205-de5a5500-bf58-11e9-9d9e-c681aa6a6ab8.png)

You need to obtain libopenblas.so (and sudo support is still on the backlog (https://github.com/microsoft/AzureNotebooks/issues/303#issuecomment-424584826) so you need to get it somehow e.g.

curl -o libopenblas.so https://raw.githubusercontent.com/DiffSharp/DiffSharp/master/lib/OpenBLAS-v0.2.14-Linux64/libopenblas.so

**Comment by cgravill** [comment]
Updating the F# Notebooks on Azure Notebooks would also be great.

Somewhat related, we're also working on on a .NET Core version of https://github.com/fsprojects/IfSharp which is starting to work enough.

**Comment by allisterb** [comment]
Oh ok if I can restore it on Azure Notebooks then that's all I need. I'll close this for now. Thanks for the response.
