### ISSUE TITLE
Link to DiffSharp on F# Foundation and license.

### ISSUE THREAD

**Issue by philderbeast** [DiffSharp/DiffSharp#61]
In referencing DiffSharp, the [F# Foundation is saying](https://fsharp.org/guides/math-and-statistics/) this library has a GPLv3 license but this repo lists the license as BSD-2.

**Comment by dsyme** [comment]
Thanks, fixed https://github.com/fsharp/fsfoundation/commit/0905321fae143686225b7b919b6a45d2978d0cd1
