### ISSUE TITLE
Notes on BERT on DiffSharp

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#67]
@moloneymb has ported BERT to work over Tensorflow.NET, https://github.com/moloneymb/BERTInFSharp/.  Just a sample and not for production.

We're doing an investigation of what it would mean to do this over DiffSharp instead of TF.NET

This is a discussion thread about what additions/changes/updates/... would be needed to DiffSharp 1.0 (dev branch) to allow this.

**Comment by dsyme** [comment]
Here are some notes made by @moloneymb on the TF nodes used by BERT in inference and training

https://github.com/moloneymb/BERTInFSharp/blob/master/OpsNeeded.md

**Comment by dsyme** [comment]
closing old issue

**Comment by fwaris** [comment]
This is old but there is now BERT for TorchSharp [nuget: TsBert](https://www.nuget.org/packages/TsBERT/). It can use pre-trained weights form Tensorflow checkpoints via [nuget: TfCheckpoint](https://www.nuget.org/packages/TfCheckpoint/).

Write-up and explanation [in this .net interactive notebook](https://github.com/fwaris/BertTorchSharp/blob/master/saved_output.ipynb)
