### ISSUE TITLE
Incorporate MXNet backend?

### ISSUE THREAD

**Issue by dsyme** [DiffSharp/DiffSharp#68]
@kevmal has done an MXNet backend for DiffSharp https://github.com/kevmal/DiffSharp/tree/mxnet

This issue is to discuss whether this should this be integrated into DiffSharp.

**Comment by dsyme** [comment]
@kevmal Do you have any thoughts about this?

**Comment by kevmal** [comment]
What's the plan for backends in general? OpenBLAS, MKL, CUDA, OpenCl, ILGPU(?) and such all make sense. Seeing Torch as a possible backend I think MXNet  fits along the same category. I could factor out the MXNetSharp dependency, making it a fairly lightweight addition. 

Downside is to use the backend the libmxnet dependency would still need to be satisfied requiring a build per platform possibly with different build options (MKL, OpenBLAS, CUDA, ...). But I'd imagine native dependencies will be a given at some point with other backend choices as well.

Upside It would add a quick GPU option and would make testing easier as DIffSharp progresses.

**Comment by moloneymb** [comment]
I'm of the opinion that a lightweight MxNet would be great. It'll be a pain to try to interface with all the lower level native libraries directly.

We're going to have to bite the native bullet anyway. Tensorflow.Net does it through reference packages in NuGet. It's not as smooth as we'd like but it is serviceable.

**Comment by dsyme** [comment]
One concern is to not get in Gunes' way too much as he finishes the API design and convolution/probabilities  support, while still expanding out the capabilities of the library. It's absolutely crucial that Gunes gets the core tensor operators in place and they are tractable and well tested. The current testing is excellent and we should ensure to always test all new code that comes in at least as well. 

I think we're close to a point where adding one native backend would still be tractable. 

I'd also like to draft a NumSharp CPU backend, as it might be really simple.

It's a very enjoyable code base to work on, let's keep it like that too :-)

**Comment by dsyme** [comment]
@kevmal I took a look at https://github.com/DiffSharp/DiffSharp/compare/dev...kevmal:mxnet and submitted a PR to bring it up-to-date in part.

The code needed for the backend is quite large and will need further updates as we complete the core of DiffSharp 1.0, both the core logical features @gbaydin is doing and things like #73.   We should probably plan on preparing an integration in a month or two once the core of DiffSharp 1.0 is stable and fully tested.

**Comment by kevmal** [comment]
> The code needed for the backend is quite large and will need further updates as we complete the core of DiffSharp 1.0, both the core logical features @gbaydin is doing and things like #73. We should probably plan on preparing an integration in a month or two once the core of DiffSharp 1.0 is stable and fully tested.

I can commit time to keeping it up to date.

> One concern is to not get in Gunes' way too much as he finishes the API design and convolution/probabilities support, while still expanding out the capabilities of the library. It's absolutely crucial that Gunes gets the core tensor operators in place and they are tractable and well tested. The current testing is excellent and we should ensure to always test all new code that comes in at least as well.

Just spitballing... One possibility is open up creating backends in separate packages requiring no update to DiffSharp? Otherwise the changes in Diffsharp are minimal, tests I would assume would be ran across backends. As far as getting in Gunes way I guess stubs would need to be created in every backend as ops are added.

> I'd also like to draft a NumSharp CPU backend, as it might be really simple.

Don't see a huge benefit here personally. Would it be significantly better than the current backend? Honestly I don't know the answer perhaps it would have similar performance to some of the native options for CPU? In the end the same concern would be as stated above so the benefit needs to be there.. But watching DiffSharp over the years the big thing was hoping to see GPU. Forgetting MXNet for a sec I'd say ILGPU would be a great backend, GPU support with no native dependencies support (don't even need CUDA SDK).

**Comment by dsyme** [comment]
> Just spitballing... One possibility is open up creating backends in separate packages requiring no update to DiffSharp? 

Yes, eventually - the Backend API pretty much allows this really - just a few tweaks to make that happen. However the Backend API will be unstable for a long time so a tight set of backends we care about will be simpler.

Re NumSharp: 

> Don't see a huge benefit here personally. Would it be significantly better than the current backend? Honestly I don't know the answer perhaps it would have similar performance to some of the native options for CPU? In the end the same concern would be as stated above so the benefit needs to be there.. But watching DiffSharp over the years the big thing was hoping to see GPU. Forgetting MXNet for a sec I'd say ILGPU would be a great backend, GPU support with no native dependencies support (don't even need CUDA SDK).

Yes, GPU support in the backends is much more important - absoltuely critical. That said I would expect a NumSharp backend to have much more performant CPU support than `DiffSharp.Backend.None`, which is naive code.  It would also be a good test for each.

**Comment by gbaydin** [comment]
I suggest backend efforts to wait until I'm done with implementing the minimal core set of operations for common modern machine learning code. It's getting there, but not there yet. `Tensor` and `RawTensor` APIs are subject to change.

My own plan with the backend is to make one based on

**Comment by gbaydin** [comment]
I suggest not undertaking any backend work until I'm done with implementing the minimal core set of operations needed for modern machine learning applications. It's getting there, but it's not there yet. 

When I'm done with this, my plan is to make the following two backends as a minimum:
- openblas, the low-level p/invoke code for this is already in place in DiffSharp master branch and it will be straightforward to port it
- libtorch (cpu and gpu), I already experimented with doing this in code I have not committed to the repository yet. The best option as I see it is to depend on LibTorch.Redist https://www.nuget.org/packages/LibTorch.Redist/ (ideally it needs to be maintained and kept up to date with each new libtorch release). That package comes with all platform-specific binaries needed for torch + MKL on windows, mac os and linux.

**Comment by dsyme** [comment]
@gbaydin Sounds good, thanks for the update on the plan.  

@kevmal The existing MXNet prototype is enough for us to see that it's going to be possible without much pain, once the Backend API is stabilised.  I guess we can aspire to keep the branch up to date (if fail then we do a full rewrite later)

@gbaydin From playing with #77 we should finalize the set of tensor types to be supported and incorporate them into Backend.None (e.g #77 ) *before* we start writing backends.  This is because the full range of tensor types currently need to be supported by each backend and there is currently going to be some code duplication here for each backend. (There's also an alternative where we adjust the backend API to allow a single generic type to implement all of them)

**Comment by dsyme** [comment]
Closing for now as this is not part of 1.0, though the backend API will be documented
