### ISSUE TITLE
Implement norm and matrix inverse

### ISSUE THREAD

**Issue by gbaydin** [DiffSharp/DiffSharp#93]
Can be equivalent to https://pytorch.org/docs/stable/torch.html#torch.norm

**Comment by cgravill** [comment]
https://pytorch.org/docs/stable/linalg.html#torch.linalg.norm would be useful for some code I'm trying to port to DiffSharp 1.0

**Comment by gbaydin** [comment]
Matrix inverse implemented in #364

**Comment by gbaydin** [comment]
TorchSharp updated in #368 to latest to introduce the norms needed to close this issue.

**Comment by gbaydin** [comment]
Norm implemented in #369.
