### ISSUE TITLE
Implement boolean tensors

### ISSUE THREAD

**Issue by gbaydin** [DiffSharp/DiffSharp#94]

**Comment by dsyme** [comment]
I think this is in here: https://github.com/DiffSharp/DiffSharp/pull/77

Do you want me to bring this up-to-date?

**Comment by gbaydin** [comment]
Oh cool, thank you for the reminder! I will check it and see if we can merge soon.

**Comment by gbaydin** [comment]
Closing this as boolean tensors are now merged as a part of #77
